// [nombre ES (clave exacta del catálogo), técnica en inglés]
module.exports = [
["Press de banca plano con barra", "Retract your shoulder blades and keep your feet firmly on the floor. Lower the bar until it grazes your chest (sternum line), elbows at ~75° from your torso. Full range, no bouncing."],
["Press de banca inclinado con barra", "Incline bench at 30-45°. Grip slightly wider than shoulder width. Lower the bar in a controlled way to the upper chest (collarbone). Press the bar up in a vertical motion."],
["Press de banca inclinado con mancuernas", "Bench at 30-45°. Press the dumbbells up and slightly inward. Control the descent for 2-3 sec; don't let your elbows drop below the plane of the bench."],
["Flexiones de brazos (peso corporal)", "Hands shoulder-width apart, body in a straight line from heels to head. Lower your chest until it almost touches the floor; elbows at ~45° from your torso."],
["Aperturas con mancuernas", "Flat or incline bench. Lower the dumbbells in an arc with slightly bent elbows until you feel a stretch in your chest. Don't overextend the range, to protect your shoulders."],
["Fondos en paralelas (pecho bajo/tríceps)", "To emphasize the chest: lean slightly forward, elbows out. Lower until your shoulders are below your elbows. Push up without locking your elbows."],
["Cruce de poleas", "Cables at shoulder height or above. Bring your hands to the center and cross slightly, squeezing your chest at the end of the movement. Controlled movement throughout."],
["Dominadas (peso corporal)", "Overhand grip, hands shoulder-width apart. Start the movement by retracting your shoulder blades. Pull up until your chin clears the bar; lower in a controlled way."],
["Jalón al pecho en polea", "Overhand grip, shoulder-width apart. Lean back slightly (10-15°) and bring the bar to your collarbone, squeezing your lats. Control the return."],
["Remo con barra", "Flat back, hip hinge to ~45°. Pull the bar toward your navel, elbows close to your body. Retract and depress your shoulder blades at the end. Don't round your lower back."],
["Remo unilateral con mancuerna", "Support your hand and knee on the bench. Back parallel to the floor. Pull the dumbbell toward your hip, rotating your torso slightly. On the way down, fully extend your shoulder blade."],
["Remo sentado en polea", "Sit upright and grab the cable with elbows close to your body. Pull until the handle touches your abdomen, squeezing your shoulder blades. Don't use torso momentum."],
["Pull-over con mancuerna", "Support only your upper back on a bench. Hold a dumbbell with both hands. With slightly bent elbows, lower the dumbbell behind your head in an arc until you feel the stretch. Raise it in a controlled way."],
["Remo en T", "Place one end of the bar in a corner. Grab the other end with a handle. Straight back and torso leaning at ~45°. Pull the bar toward your chest, keeping your elbows close and squeezing your back."],
["Hiperextensiones lumbares", "Hips resting on the Roman chair. Lower your torso to ~90° and rise until your body is in a straight line (don't hyperextend). Glutes active as you rise."],
["Sentadilla libre", "Feet shoulder-width apart, toes slightly turned out. Lower while keeping your torso upright and your knees aligned with your feet. Minimum depth: thighs parallel to the floor."],
["Prensa de piernas", "Back and glutes against the backrest. Feet on the platform shoulder-width apart. Lower until your knees form ~90° without lifting your glutes off the seat."],
["Zancadas / estocadas", "Take a wide step forward. The back knee almost touches the floor; the front knee should not go past your toes. Torso upright throughout the movement."],
["Peso muerto rumano", "Slightly bent knees, hip hinge: lower the bar sliding it down your legs until you feel the stretch in your hamstrings. Neutral back at all times."],
["Hip thrust (empuje de cadera)", "Shoulders resting on the bench, bar over the crease of your hips. Push until your hips, thighs and torso form a straight line. Squeeze your glutes at the top."],
["Extensión de cuádriceps en máquina", "Adjust the seat so your knee joint lines up with the machine's pivot. Extend fully and hold for 1 sec; lower in a controlled way (2-3 sec)."],
["Curl femoral tumbado o sentado", "Hips pressed against the bench. Curl to ~120-130° (peak hamstring contraction); extend slowly without locking your knee at the end."],
["Elevación de talones", "Stand on the edge of a step. Lower your heel below the level of the step for maximum stretch; rise onto your toes as high as possible. Pause at the top for 1 sec."],
["Sentadilla búlgara", "Rear foot resting on the bench, front foot far enough forward so your knee doesn't pass your toes. Lower in a controlled way until the back knee almost touches the floor."],
["Peso muerto sumo con barra", "Feet much wider than shoulder width, toes pointing out. Grip inside your legs. Keep your torso upright and lower your hips. Push the floor away with your legs, keeping the bar close to your shins."],
["Step-ups con mancuernas", "Hold a dumbbell in each hand. Place one foot on a stable box. Push your body up mainly with the leg on the box, without pushing off much with the trailing leg. Lower in a controlled way."],
["Press militar con barra o mancuernas", "Standing or seated. Press the bar/dumbbells vertically overhead until your arms are almost extended. Don't arch your lower back when locking out."],
["Elevaciones laterales con mancuernas", "Slightly bent elbows. Raise until your arms are parallel to the floor (no higher). A slight external rotation at the end: pinky slightly higher than thumb."],
["Pájaros / vuelos posteriores", "Torso bent ~90°. Raise the dumbbells with slightly bent elbows until they line up with your shoulders, squeezing your rear delts."],
["Elevaciones frontales", "Standing, dumbbells in front with a neutral or overhand grip. Raise to eye level (no higher). Avoid swinging your torso."],
["Face pull (salud del hombro)", "High cable with a rope. Pull toward your face, separating the rope and externally rotating your shoulders. Elbows above the grip. Focus on the rear delts and rotator cuff."],
["Press Arnold", "Seated with dumbbells at shoulder level and palms facing you (supinated). As you press the dumbbells up, rotate your wrists so that at the top your palms face forward (pronated)."],
["Encogimientos de hombros con barra reversa", "Hold the bar behind your back. Keep your arms straight and raise your shoulders toward your ears, shrugging your traps. Hold the contraction for 1-2 sec at the top and lower in a controlled way."],
["Curl de bíceps con barra", "Elbows tucked at your sides. Curl the bar in a controlled arc to peak contraction; lower slowly (2-3 sec). Don't use torso momentum."],
["Curl martillo con mancuernas", "Neutral grip (thumbs up). Elbows fixed at your sides. Curl up to the contraction and lower in a controlled way. Works the brachialis and brachioradialis in addition to the biceps."],
["Curl predicador", "Arms resting on the angled pad. Avoid swinging and fully locking out at the bottom to maintain tension. Focus on the lower part of the biceps."],
["Press francés", "EZ bar, lying down. Elbows pointing at the ceiling, fixed. Lower the bar to your forehead or behind your head (greater stretch). Extend without fully locking out."],
["Extensión de triceps en polea alta", "Rope or bar on a high cable. Elbows fixed at your sides. Extend to peak triceps contraction; return in a controlled way."],
["Fondos entre bancos", "Hands on the bench behind you, feet on the front bench or on the floor. Lower until your elbows form 90°; push up without fully locking out. Torso upright to focus on the triceps."],
["Extensión de tríceps con mancuerna sobre la cabeza", "Seated or standing. Hold a dumbbell with both hands overhead. Elbows close to your ears; lower the dumbbell behind your head, controlling the stretch of the long head of the triceps."],
["Patada de tríceps con mancuerna", "Torso parallel to the floor, elbow raised to hip height. Extend your forearm back to peak contraction; return in a controlled way. Elbow fixed."],
["Curl de muñeca con barra", "Forearms resting on the bench or your thighs. Curl your wrist through a full range; lower with control. Light weight, high reps."],
["Curl de muñeca con mancuerna", "Same as with the bar, but allows a greater individual range of motion per wrist. Work one arm at a time to correct imbalances."],
["Curl invertido con barra", "Overhand grip (back of the hand up). Elbows fixed at your sides. Works the forearm extensors and brachioradialis. Keep your wrist neutral as you curl."],
["Farmer's walk (caminata del granjero)", "Heavy load in both hands. Straight back, shoulders back and down. Walk with medium, firm steps. Focus on grip and core stability."],
["Plancha abdominal", "Forearms and feet on the floor. Activate your core (pull your navel toward your spine). Body in a straight line; don't raise your hips or let them sag."],
["Crunch abdominal clásico", "Lying down, knees bent. Lift only your shoulders off the floor by curling your spine (not your hips). Squeeze your abs at the top; lower in a controlled way."],
["Elevación de piernas colgado o en suelo", "Hanging from a bar: pelvis slightly tucked. Raise your legs straight (or bent) to horizontal or higher. Avoid swinging."],
["Giros rusos", "Seated with your torso at ~45°, feet raised (optional). Rotate your torso from side to side with control; not just your arms. Use a plate or dumbbell to add resistance."],
["Rueda abdominal", "Knees on the floor. Roll forward extending your hips and spine almost to the floor; return by activating your core without momentum. A very demanding exercise."],
["Dragon flag", "Lying down, hold a fixed bench behind your head. Keep your body straight and tight. Raise your legs and torso together until you rest only on your shoulders. Lower in a controlled way without bending."],
["Burpees", "Stand → squat down → plank → push-up (optional) → jump with your arms overhead. Keep your core engaged throughout the whole sequence."],
["Saltos de tijera", "Feet together at the start. Jump, opening your legs and arms at the same time; land softly on the balls of your feet with slightly bent knees."],
["Salto a la cuerda", "Feet together or alternating, knees slightly bent. Your wrists turn the rope (not your shoulders). Land softly on the balls of your feet."],
];
