// [índice de catálogo (primer campo en scripts_datos/nuevos/*.js), técnica en inglés]
module.exports = [
// ── Pecho ──
[288, "Lying on a flat bench, lower the dumbbells to chest level with your elbows at ~60-75° from your torso and press up, bringing them together without clanking. Shoulder blades retracted and feet firm on the floor."],
[311, "On a decline bench, lower the dumbbells toward your lower chest in a controlled way and press in a vertical line. Keep your wrists straight and your elbows at ~60° from your torso."],
[295, "Bench at 30°. With slightly bent elbows, open your arms in an arc until you feel the chest stretch and return, bringing the dumbbells together at the top without clanking them."],
[283, "Cables at ankle height and torso leaning slightly forward. Raise your arms in an arc until your hands meet at chest level, squeezing your upper chest."],
[284, "Cables at the top, one foot forward for stability. Bring your hands down and forward in an arc until they meet in front of your abdomen, with elbows slightly bent."],
[281, "Sit with your back flat against the pad and your elbows at chest height. Bring your arms together in front squeezing your chest and return controlling the stretch without lifting your back."],
[1053, "Adjust the seat so the handles are at mid-chest height. Press without locking your elbows and return controlling for 2-3 seconds, with your back supported."],
[315, "With the backrest fixed and the handles at upper-chest height, press up and forward without shrugging your shoulders. Control the return."],
[761, "Grip the bar wider than your shoulders and lower it until it grazes your chest with your elbows flared more. Puts greater emphasis on the outer chest; don't bounce the bar."],
[762, "On a decline bench, lower the bar to your lower chest and press in a straight line. Use safeties or a spotter to unrack and re-rack the bar safely."],
[552, "Place your hands on a stable bench, chair or step and keep your body in a straight line. Lower your chest toward the support and push. This is the easiest version of the push-up."],
[478, "Rest your knees on the floor, body straight from knees to head and hands under your shoulders. Lower your chest almost to the floor and push without arching your lower back."],
[1231, "With your feet on a bench or chair and your hands on the floor, lower your chest in a controlled way and push. Emphasizes the upper chest and shoulders; keep your core tight."],
[593, "Lower your chest to the floor and push up so explosively that your hands leave the floor to clap. Land with slightly bent elbows. Explosive exercise for advanced level."],
[1132, "With your hands very wide, lower your body toward one hand while the opposite arm stays extended, and alternate sides. Works the chest unilaterally."],
[1166, "In a push-up position, lower and push up and, at the top, touch one shoulder with the opposite hand without rotating your hips. Combines chest and core stability."],
[1052, "Lying on a bench with palms facing each other, press the dumbbells up keeping your elbows close to your body. Reduces tension on the shoulders."],
[924, "Seated with your back supported, push the cable handles forward until your elbows are almost extended and return in a controlled way. The cable's constant tension keeps your chest working."],
[290, "Standing sideways to the cable, push a single handle forward without rotating your torso. Works the chest and anti-rotation core; repeat on both sides."],
[840, "Incline bench between two low cables. Open your arms in an arc with slightly bent elbows and bring them together over your upper chest, squeezing."],
[1136, "Band anchored behind your back or to a fixed point. With slightly bent elbows, bring your hands together in front in an arc squeezing your chest and return in a controlled way."],
[1126, "From an inverted V position, lower your chest in an arc toward the floor and rise into a cobra pushing with your arms; reverse the movement. Combines chest, shoulders and mobility."],
// ── Espalda ──
[712, "Underhand grip at shoulder width. Pull up until your chin clears the bar, driving your elbows toward your hips, and lower without swinging. Greater biceps involvement."],
[1100, "With parallel handles, pull up until your chin clears the bar and lower all the way down. A comfortable position for shoulders and elbows, with great lat work."],
[454, "Choose a counterweight that lets you complete the reps with good technique. Pull your chest to the bar and lower in a controlled way; reduce the assistance progressively."],
[1155, "Loop a resistance band over the bar and rest your knees or feet in it. Pull your chest toward the bar and lower in a controlled way; use thinner bands as you progress."],
[509, "Sit with your torso leaning back slightly and pull the V-handle toward your chest, bringing your shoulder blades together. Return by stretching fully without losing tension."],
[618, "Narrow neutral grip: pull toward your upper chest keeping your elbows close to your body. Emphasizes the lower part of the lats."],
[230, "Standing in front of the high cable, with almost straight arms pull the bar down to your thighs by contracting your lats. Don't bend your elbows or use torso momentum."],
[490, "With one hand on the handle, pull toward your shoulder driving your elbow toward your hip. Allows a greater range of motion and corrects imbalances between sides."],
[224, "Adjust the thigh pad and pull the handles to your upper chest keeping your chest upright. Return in a controlled way until your arms are straight."],
[240, "With your chest supported, pull the handles toward your abdomen bringing your shoulder blades together and return by stretching without lifting your torso off the pad."],
[506, "Seated with a straight back, pull the V-handle toward your lower abdomen, bring your shoulder blades together and return by stretching without rounding your lower back."],
[619, "Pull the rope toward your chest, slightly spreading your hands at the end of the movement. Keep your chest up and your elbows close to your body."],
[241, "Standing or seated, pull a single handle toward your hip without rotating your torso. Allows a good range and corrects imbalances between sides."],
[242, "With your torso leaning ~45° and your back straight, pull the bar with an underhand grip toward your abdomen. Greater work for the lower lats and biceps."],
[994, "Torso parallel to the floor. Pull the bar explosively from the floor toward your abdomen and return it to the floor on every rep, with a neutral back."],
[540, "With your chest supported on an incline bench, pull the bar toward your abdomen without momentum. Eliminates swinging and protects your lower back."],
[235, "Lean your torso with a straight back and pull both dumbbells toward your hips, bringing your shoulder blades together. Lower in control until your arms are stretched."],
[443, "Lying face down on an incline bench, pull the dumbbells with an underhand grip toward your ribs. No momentum from your legs."],
[1110, "Lying face down on a high bench, pull the dumbbells toward your ribs and lower in a controlled way. Isolates the back with no load on your lower back."],
[695, "Torso leaning with a neutral back and the kettlebell hanging; pull toward your hip driving your elbow back and lower with control. Alternate arms."],
[466, "Lying under a sturdy table, grab the edge and pull your chest toward it with your body straight. An excellent at-home option for the back."],
[644, "Under a bar at hip height, pull your chest toward the bar with your body in a straight line. The more horizontal, the harder."],
[984, "Seated with your legs extended and the band around your feet, pull the ends toward your abdomen bringing your shoulder blades together and return with control."],
[1190, "Band anchored at chest height; pull the ends toward your torso with your elbows tucked and your back straight. Return slowly."],
[249, "Bar over the middle of your foot, grip shoulder-width, neutral back and chest up. Push the floor away with your legs and extend your hips without rounding your back."],
[991, "Bar on the safeties at knee height. Extend your hips and knees keeping your back straight and squeeze your glutes and lats at the top. Lets you load more on the upper-back portion."],
[800, "Hanging from the bar with straight arms, raise your body only by moving your shoulder blades down and back, without bending your elbows. Improves shoulder and lat control."],
[996, "Lying face down, raise your arms and legs off the floor at the same time squeezing your glutes and lower back. Hold for 1-2 seconds at the top and lower with control."],
[614, "On all fours, extend the opposite arm and leg while keeping your back neutral and your hips still. Alternate sides with control."],
[468, "Supported face down on the machine, raise your legs until they line up with your torso squeezing your glutes and lower back. Don't swing with momentum."],
[312, "Bar on your upper back, knees slightly bent. Lean your torso forward by pushing your hips back with a straight back and return squeezing your glutes."],
[50, "Hold a dumbbell against your chest or shoulders. Push your hips back leaning your torso with a neutral back and return by extending your hips."],
];
