// [índice de catálogo, técnica en inglés]
module.exports = [
// ── Piernas ──
[744, "Bar resting on the front of your shoulders with your elbows high. Lower with an upright torso to parallel or below and push the floor away to rise. Greater quad emphasis."],
[317, "Back against the backrest and feet shoulder-width apart. Lower until your thighs are parallel or lower and push without locking your knees at the top."],
[338, "Bar on your upper back, take a long step and lower until both knees form ~90°. Push through your front heel to return. Alternate legs."],
[914, "Upper back supported and feet firm on the platform. Drive your hips up squeezing your glutes and lower in a controlled way without losing tension."],
[364, "Support your chest and push the platform back with your heel, extending your hip and squeezing your glute. Return in a controlled way without arching your lower back."],
[1050, "Seated with your back supported, open your legs against the pads and return slowly. Works the gluteus medius and the outer hip."],
[1049, "Seated, bring your legs together against the pads squeezing your inner thighs and return in a controlled way through the full range."],
[742, "Standing inside the hex bar, neutral back and chest up. Push the floor away with your legs until you are upright and lower with control. A back-friendlier posture."],
[316, "With the dumbbells in front of your thighs, push your hips back with slightly bent knees until you feel the hamstring stretch. Rise by squeezing your glutes."],
[810, "With your knees almost straight, lower the bar close to your legs leaning your torso with a straight back. A big hamstring stretch; rise by extending your hips."],
[1147, "Standing on one leg, lean your torso lowering the dumbbell toward the floor while the other leg lifts behind you. Square hips and neutral back."],
[606, "Balancing on one leg, lean your torso forward lifting the other leg behind you and reaching your arms toward the floor. Hips level. Improves balance and hamstrings."],
[38, "Hold a dumbbell against your chest, feet shoulder-width apart. Lower between your knees with an upright torso and rise by pushing the floor away. Ideal for learning the squat."],
[345, "Feet shoulder-width apart, push your hips back and down with a straight back and your knees in line with your feet. Rise by pushing the floor away. The foundation of any at-home training."],
[331, "Feet wider than your shoulders and toes pointing out. Lower with an upright torso and your knees following the line of your feet. Works the adductors and glutes."],
[1048, "Wide feet and toes pointing out, dumbbell hanging between your legs. Lower keeping your chest up and rise squeezing your glutes and adductors."],
[36, "With your feet far apart, shift your weight to one side bending that knee while the other leg stays extended. Rise and alternate. Works the adductors and glutes."],
[59, "Take a long step forward and lower until both knees form ~90° with an upright torso. Push through your front heel to return. Alternate legs."],
[621, "Take a long step back and lower your back knee toward the floor with an upright torso. Less stress on the knee than the forward lunge."],
[1033, "With a dumbbell in each hand, step back and lower to ~90° in both knees, keeping your trunk firm. Push through your front foot to return."],
[328, "Dumbbells at your sides, take a long step forward and lower in a controlled way until your knees form ~90°. Push through your front heel to return."],
[47, "Step forward alternating legs with a dumbbell in each hand, lowering your back knee close to the floor on every step. Keep your torso upright."],
[570, "Step forward alternating legs, lowering your back knee toward the floor on every step and pushing through your front leg. Straight torso and long strides."],
[341, "Take a wide step to the side and bend that knee pushing your hips back while the other leg stays extended. Push to return. Works the adductors and glutes."],
[39, "Take one leg back and diagonally, crossing behind the other, and lower to ~90°. Return to the starting position. Works the gluteus medius and quads."],
[505, "With your upper back supported on a bench or sofa, drive your hips up until they line up with your torso, squeezing your glutes for 1-2 seconds at the top. Lower in a controlled way."],
[1025, "Lying on your back with bent knees, raise your hips squeezing your glutes until your shoulders, hips and knees form a line. Lower slowly. Ideal for activating the glutes."],
[635, "With a dumbbell on your hips, raise your pelvis squeezing your glutes until your torso and thighs line up. Lower in a controlled way without fully resting."],
[525, "With one leg extended in the air, raise your hips with the other leg squeezing your glute. Keep your pelvis level and lower in a controlled way."],
[938, "Band above your knees. Raise your hips pushing your knees out against the band to add gluteus medius work."],
[946, "Band around your thighs or ankles with slightly bent knees. Take wide side steps keeping tension on the band and your hips level."],
[949, "On all fours with the band around your feet or above your knees, extend one leg back squeezing your glute without arching your back."],
[953, "On all fours with the band above your knees, open one knee out to the side against the band keeping your pelvis stable. Works the gluteus medius."],
[997, "On all fours, lift one knee out to the side keeping the 90° angle and a stable pelvis. Lower in a controlled way and repeat on both sides."],
[1005, "On all fours, push your heel toward the ceiling with a bent knee until your thigh lines up with your back, squeezing your glute. Lower without resting."],
[347, "Lying on your side with your knees bent and feet together, open your top knee without moving your pelvis and return. Activates the gluteus medius."],
[324, "Standing on one leg with the other extended in front, lower in a controlled way into a deep squat and rise without touching down with the free leg. Requires strength, balance and mobility."],
[8, "Hold a dumbbell in one hand and rise onto your toes on a step or the floor, pause at the top and lower until your calf is stretched. Full range."],
[366, "Balancing on one leg, rise onto your toes as high as possible and lower slowly until stretched. Hold a wall for balance. Add load with a dumbbell."],
[340, "Seated in the leg press with your legs almost extended, push the platform only with the balls of your feet and return stretching your calf. Don't lock your knees."],
[365, "With your knees bent under the pad, raise your heels as high as possible and lower until stretched. Mainly works the soleus."],
[465, "Bar on your upper back, rise onto your toes on a platform and lower until stretched below the step. Keep your torso upright."],
[774, "Lying on your back with your heels on towels on a smooth floor, raise your hips and slide your heels away and back. Hamstrings at home with no equipment."],
[959, "With the band anchored, bend your knee bringing your heel toward your glute and return in a controlled way. Keep your hips stable."],
[987, "Lean your torso back while your knees move forward and your heels rise. Great quad isolation. Hold onto a support for balance."],
[1085, "With your feet anchored and your body straight, lower your torso in a controlled way and rise bending your knees using your hamstrings and glutes. Very demanding; use assistance if needed."],
[358, "With the ankle strap on a low cable, extend your leg back squeezing your glute without arching your lower back and return in a controlled way."],
[1139, "With a band above your knees and your upper back supported on a bench, drive your hips up opening your knees against the band and squeeze at the top."],
// ── Hombros ──
[37, "Seated with your back supported, lower the bar to chin height and press up until your elbows are almost extended. Abs firm; don't arch your back."],
[116, "Adjust the seat so the handles are at shoulder height. Press up without locking your elbows and lower in a controlled way."],
[114, "Standing sideways to the low cable, raise your arm out to the side to shoulder height with a slightly bent elbow. Keep constant tension on the way down."],
[409, "With your elbows against the pads, open your arms to shoulder height and lower in a controlled way. Isolates the lateral deltoid."],
[163, "Seated facing the backrest, open your arms back bringing your shoulder blades together without shrugging. Return in a controlled way."],
[169, "With two crossed cables, open your arms back and out with slightly bent elbows, squeezing the rear deltoid."],
[172, "Pull the bar or rope up close to your body to chest height with your elbows above your wrists. Don't go higher if it bothers your shoulder."],
[178, "With a dumbbell in each hand in front of your thighs, raise your elbows up and out to chest height. Lower in a controlled way."],
[1045, "Shoulder-width grip, pull the bar up close to your torso to chest level with your elbows high. Avoid swinging and raising it too high."],
[891, "Sitting on the floor with your legs extended, press the dumbbells overhead without back support. Requires a very stable core."],
[425, "Standing or seated, press one dumbbell overhead without leaning your torso and lower in a controlled way. Works the shoulder and core stability."],
[430, "Standing, press one dumbbell up while the other comes down, alternating arms with a firm torso and no arching of your back."],
[599, "Kettlebell in the rack position, press up until your arm is extended in line with your ear. Squeeze your glute and abs; lower in a controlled way."],
[741, "With the kettlebells at shoulder height and your wrists straight, press up and lower in a controlled way. Stabilizer and shoulder strength."],
[665, "Step on the band or anchor it under your feet. Press the ends overhead until your arms are extended and lower slowly. A great at-home option."],
[411, "Hold the band in front of you with your arms extended and pull it apart to your chest bringing your shoulder blades together. Return slowly. Excellent for posture and the rear deltoid."],
[1102, "With your torso leaning and the band under your feet, open your arms out to the sides to shoulder height. Control the return."],
[426, "Raise your arms diagonally (30° in front of you) with your thumbs up to shoulder height. Safer for the rotator cuff."],
[428, "Raise the dumbbells with a high elbow to shoulder height, rotate your forearms up and press overhead. Works the shoulder and rotator cuff."],
[963, "Elbow tucked at your side at 90°, rotate your forearm outward against the band and return slowly. Strengthens the rotator cuff and prevents injuries."],
[532, "Lying face down on an incline bench, open your arms out to the sides with slightly bent elbows, squeezing the rear deltoid."],
[533, "Lying face down on an incline bench, raise your arms forming a Y with your thumbs up. Works the rear deltoid and lower trapezius."],
[688, "With your hips raised forming an inverted V, lower your head between your hands and push back up. A great shoulder exercise with no equipment."],
[48, "Slightly bend your knees and drive explosively with your legs to propel the dumbbells overhead. Lower in a controlled way."],
[293, "Bar on your shoulders, bend your knees and extend forcefully to drive the bar overhead. Lock out at the top with a firm core."],
[144, "Combines a front raise, lateral raise, rear raise and cross raise with light dumbbells. Keep control on each of the four paths without swinging your torso."],
[148, "Dumbbells at your sides, raise your shoulders toward your ears, pause at the top and lower in a controlled way. Don't roll your shoulders. Works the upper trapezius."],
[151, "With the bar in front of your thighs, raise your shoulders vertically as high as possible and lower slowly. Don't bend your elbows."],
[150, "Facing the low cable, shrug your shoulders toward your ears with the cable's constant tension and lower in a controlled way."],
[155, "Seated or standing at the machine, raise your shoulders vertically and lower in a controlled way. Useful for loading the traps safely."],
[56, "Standing with your feet hip-width apart, press the dumbbells from your shoulders overhead without arching your back and lower in a controlled way."],
];
