// [índice de catálogo, técnica en inglés]
module.exports = [
// ── Brazos (bíceps) ──
[251, "Standing with a dumbbell in each hand and your elbows tucked at your torso, bend your elbows until your biceps contract and lower in a controlled way without swinging your body."],
[259, "Seated with your elbow resting on your inner thigh, curl the dumbbell toward your shoulder and lower slowly. Maximum biceps isolation."],
[270, "Seated on an incline bench at ~45° with your arms hanging, bend your elbows without moving them forward. A big biceps stretch at the bottom."],
[480, "Curl the dumbbells with a supinated grip, rotate your wrists at the top to an overhand grip and lower slowly in that position. Works the biceps, brachialis and forearm."],
[268, "With your arms resting on the preacher bench, lower the bar until your elbows are almost extended and curl up without lifting your arms off the pad. Avoid momentum."],
[276, "Adjust the seat so your arms rest on the pad and bend your elbows against the resistance. Control the full descent."],
[267, "One arm at a time resting on the preacher bench, bend your elbow until your biceps contract and lower slowly with your arm almost extended."],
[1044, "Grip the Z-bar at the angled sections, elbows tucked at your torso, and curl to chest height. Reduces wrist strain compared to a straight bar."],
[1041, "Facing the low cable with a bar or straight handle, bend your elbows until your biceps contract and lower in a controlled way. The cable keeps constant tension."],
[538, "With the rope on a low cable and your palms facing each other, bend your elbows keeping them tucked at your body and lower in a controlled way. Works the brachialis and forearm."],
[292, "With a single handle on a low cable, bend your elbow without moving your shoulder and lower slowly. Lets you even out strength between both arms."],
[479, "Lying on the floor with your feet toward the low cable, bend your elbows bringing the bar toward your forehead while keeping your arms still."],
[485, "Standing between two high cables, bend your elbows bringing your hands toward your ears like a biceps pose. Squeeze at the top and return in a controlled way."],
[720, "Seated on an incline bench with your back to the low cable, bend your elbows keeping your arms behind you. A big stretch for the long head of the biceps."],
[975, "Step on the band with both feet and bend your elbows until your biceps contract. Control the lowering to keep tension. An inexpensive at-home option."],
[1056, "Step on the band and, with your palms facing each other, bend your elbows without lifting them from your torso. Control the return."],
[1182, "Seated with a straight back, curl one arm while the other lowers, alternating with control and rotating your wrist outward as you rise."],
[481, "With an overhand grip (palms down), bend your elbows keeping your wrists straight. Works the brachioradialis and forearm in addition to the biceps."],
[497, "Overhand grip on the EZ bar, bend your elbows with firm wrists and lower slowly. Works the brachialis and the outer part of the forearm."],
[1123, "Raise the bar by dragging it up close to your body while your elbows move back. Reduces shoulder momentum and emphasizes the biceps."],
[1149, "With your hands closer than shoulder width, bend your elbows tucked at your torso until your biceps contract and lower in a controlled way."],
[484, "Lying face down on an incline bench, let your arms hang and bend your elbows without swinging. Maximum biceps isolation."],
[1181, "With a full bottle in each hand and your palms facing each other, bend your elbows tucked at your torso and lower slowly. An at-home alternative with no dumbbells."],
// ── Tríceps ──
[258, "Standing in front of the high cable, with your elbows tucked at your torso extend your arms until they lock out at the bottom and return in a controlled way without moving your shoulders."],
[572, "With the rope on a high cable, extend your elbows and spread your hands at the end of the movement to contract the triceps more. Control the return."],
[1081, "V-handle on a high cable, elbows tucked at your body; extend down squeezing your triceps and return slowly."],
[573, "With an underhand grip on a high cable, extend your elbows keeping them tucked at your torso. Emphasizes the medial head of the triceps."],
[72, "One arm at a time on a high cable, with your elbow fixed at your side, extend down and return in a controlled way. Corrects imbalances between sides."],
[278, "Back to the cable with the rope behind your neck, extend your elbows overhead keeping them fixed. A big stretch for the long head."],
[535, "Lying on a bench, lower the dumbbells toward your temples bending only your elbows and extend at the top without flaring your arms. Keep your upper arms still."],
[291, "Lying on a bench, lower the bar toward your forehead bending only your elbows and extend at the top. Use an EZ bar if your wrists bother you."],
[489, "Seated, hold a dumbbell with both hands overhead and bend your elbows lowering it behind your neck. Extend without flaring your elbows."],
[488, "Seated with a dumbbell overhead, lower your forearm behind your neck and extend. Support your elbow with your other hand to keep it fixed."],
[539, "Seated or standing, lower the EZ bar behind your neck by bending your elbows and extend upward. Keep your core firm and your elbows close."],
[642, "Standing with the bar overhead, lower by bending your elbows behind your neck and extend with control. Don't arch your back."],
[301, "With your torso leaning and your elbow tucked at your side, extend your arm back against the cable until it locks out and return in a controlled way."],
[305, "Sitting on the floor with your hands behind your hips and your feet planted, raise your hips by extending your elbows and lower by bending them. Beginner level."],
[1040, "Hands together under your chest forming a diamond with your index fingers and thumbs. Lower your chest toward your hands with your elbows tucked and push up."],
[33, "A hybrid between a close-grip press and an extension: lower the bar toward your upper chest/chin with your elbows forward and press. Moderate loads and control."],
[1038, "Grip shoulder-width apart, elbows tucked at your torso. Lower the bar to your lower chest and press without flaring your elbows. A great strength exercise for the triceps."],
[726, "With your elbows resting on the pad, extend your arms until they lock out and return in a controlled way. Safe triceps isolation."],
[728, "Seated at the machine, push the handles down extending your elbows tucked at your body and return with control."],
[985, "With the band anchored overhead, extend your elbows down tucked at your torso and return in a controlled way. An at-home alternative to the cable pushdown."],
[976, "Lying down with the band anchored behind your head, bend your elbows toward your forehead and extend up keeping your arms still."],
[990, "Lying on a bench with the dumbbells over your chest, bend your elbows bringing the dumbbells toward your chest while flaring your elbows, and extend. Intense isolation."],
[1039, "Lying with the dumbbells over your chest and your palms facing each other, lower in a controlled way bending only your elbows and extend."],
[989, "On a decline bench, lower the dumbbells toward your forehead and extend your elbows. The angle increases tension on the triceps."],
[1080, "With your hands on a low bar or a sturdy table, lower your forehead by bending your elbows and extend your arms. The more horizontal, the harder."],
// ── Antebrazos ──
[1042, "Forearms supported with your palms facing down, extend your wrists up and lower in a controlled way. Works the forearm extensors."],
[1142, "With your forearm supported, let the dumbbell roll to your fingertips, close it back into your palm and curl your wrist. Improves grip strength."],
[1141, "Let the bar roll to your fingertips and close it back into your palm with your wrist flexed. Increases grip strength."],
[124, "With your forearm supported and your palms facing each other, curl your wrist up with the dumbbell and lower in a controlled way. Full range."],
[625, "With the bar behind your back and an overhand grip, curl your wrists up and lower in a controlled way. Short range and constant tension."],
[318, "Squeeze the gripper as hard as possible with one hand and release slowly. Works grip strength and the forearm. Handy at home or in the gym."],
// ── Abdomen / core ──
[246, "Lying with your hands behind your head, bring one elbow toward the opposite knee while extending the other leg, alternating sides with control and without pulling on your neck."],
[245, "In a high plank position, bring your knees alternately toward your chest at a steady pace with your hips stable. Works core and cardio."],
[261, "On your back with your arms and legs raised, lower the opposite arm and leg without your lower back leaving the floor. Alternate sides."],
[1030, "Lying with your arms and legs extended, raise your legs and torso at the same time forming a V and lower in a controlled way. An advanced core exercise."],
[1031, "Lying with your legs extended about 30 cm off the floor, alternate small, quick kicks keeping your lower back pressed to the floor."],
[247, "On your back with your legs raised, cross one over the other in a scissor motion keeping your abs contracted and your lower back pressed down."],
[264, "Lying on your back with bent knees, lift your pelvis off the floor bringing your knees toward your chest. Lower slowly without swinging."],
[1016, "Lying with your knees bent, raise your torso until you are sitting with your abs contracted and lower in a controlled way. Don't pull on your neck."],
[262, "With your feet anchored on a decline bench, raise your torso with your abs contracted and lower in a controlled way. Harder than on the floor."],
[97, "Standing in front of the high cable with the rope behind your neck, flex your torso downward contracting your abs without moving your hips and rise in a controlled way."],
[272, "Kneeling in front of the high cable, flex your spine bringing your elbows toward your knees and return slowly. Keep your hips still."],
[472, "Hanging from a bar, raise your knees toward your chest curling your pelvis and lower in a controlled way without swinging."],
[476, "Hanging from the bar, raise your straight legs until your feet touch the bar. Requires abs, grip and control. Advanced."],
[475, "Hanging from the bar with your legs raised, swing them from side to side like a windshield wiper with control. Very demanding for the obliques."],
[508, "Supported on one forearm and the edge of your foot, raise your hips to form a straight line from head to feet and hold. Works the obliques."],
[511, "In a plank, raise the opposite arm and leg and hold for 1-2 seconds without rotating your hips. Alternate sides."],
[1019, "In a high plank, bring your knee toward your elbow on the same side and return, alternating sides with stable hips."],
[20, "With your hands under your shoulders and your body straight from head to heels, squeeze your glutes and abs and hold the position. Breathe steadily."],
[390, "Supported on your forearms in the Roman chair, raise your straight or bent legs to horizontal without swinging and lower with control."],
[387, "Standing with a dumbbell in one hand, lean your torso toward that side and return by contracting the opposite oblique. Don't lean forward."],
[528, "Standing next to the low cable, lean your torso away from the cable and return in a controlled way. Keep your hips still."],
[926, "Standing sideways to the cable, push the handle forward and hold for 1-2 seconds resisting rotation. Works anti-rotation core strength."],
[608, "Seated at the machine, flex your torso contracting your abs and return in a controlled way. Adjust the weight to maintain technique."],
[574, "Standing next to the high cable, pull diagonally toward the opposite hip rotating your torso and control the return. Works the obliques."],
[575, "Standing next to the low cable, pull diagonally up over the opposite shoulder rotating your trunk and return slowly."],
[581, "Supported on your hands on bars or the floor, raise your body with your legs extended in front forming an L and hold. Demanding for the abs and triceps."],
[19, "On all fours with your knees a few centimeters off the floor, move forward moving the opposite hand and foot with a flat back. Core and shoulders at work."],
[254, "Lying with your knees bent to one side, raise your torso and bring your shoulder toward the opposite knee. Alternate sides."],
[15, "Standing, exhale all your air and contract your abs drawing them in and up. Hold for 15-20 seconds without inhaling. Strengthens the transverse abdominis."],
[407, "Seated with your hands behind your hips, raise your pelvis and line up your body and legs facing the ceiling. Works the glutes, lower back and posterior core."],
[14, "In a forearm plank with your feet on towels or sliders, rock your body forward and back without arching your back."],
[96, "Lying with your hands behind your neck, bring one elbow toward the opposite knee with a controlled trunk rotation and alternate sides."],
[273, "Lying with your knees bent, slightly raise your shoulders and alternately touch each heel with the hand on the same side. Works the obliques."],
// ── Cardio / acondicionamiento ──
[106, "Keep a steady, conversational pace with an upright torso and your foot landing under your body. Gradually increase time or distance."],
[133, "Walk or run at a controlled speed keeping an upright posture and without holding the rails. Adjust speed and incline to your goal."],
[134, "Walk at a firm pace on the treadmill at an 8-12% incline without holding the rails. High calorie burn with low impact."],
[132, "Adjust the saddle so your knee is almost extended at the bottom and pedal at a steady cadence. Ideal for low-impact cardio."],
[135, "Push with your legs, lean your torso and pull the handle toward your abdomen; return in reverse order. Full-body cardio."],
[137, "Keep your torso upright and push the pedals in a fluid motion, also using the moving handles. Very low joint-impact cardio."],
[138, "Climb the steps with an upright torso without putting all your weight on the rails. Great leg and glute work with intense cardio."],
[107, "Run at maximum speed for 10-30 seconds with full rest between sets. Warm up well beforehand and keep good technique."],
[401, "Run without moving, raising your knees well and pumping your arms. Ideal as a warm-up or cardio at home with no equipment."],
[402, "Lower into a squat and jump explosively extending your hips and knees. Land softly with bent knees and repeat."],
[580, "Jump vertically bringing your knees toward your chest in the air and land softly. High intensity; do it with good technique and rest between sets."],
[325, "Jogging in place, bring your heels toward your glutes alternately with an upright torso. A good hamstring warm-up."],
[1011, "Run in place raising your knees to hip height with your arms active. Quickly raises your heart rate."],
[1022, "Jump sideways from one leg to the other like a skater, crossing the free leg behind you. Works the glutes and cardio."],
[55, "Throw punches at the air with footwork and hip and shoulder rotation, keeping your guard up. Cardio, coordination and fun."],
[603, "With the kettlebell between your legs, drive your hips forward to swing it to chest height with relaxed arms. The movement comes from the hips, not the arms."],
[697, "Do the burpee holding dumbbells: chest to the floor, stand up and jump. Increases the metabolic demand; use light loads and good technique."],
[503, "Lying with a kettlebell or dumbbell in your extended arm, stand up in controlled stages and return to the floor. Total-body strength, stability and mobility."],
[1175, "Pedal and push and pull the levers at the same time; the harder you go, the more resistance. Perfect for high-intensity intervals."],
[322, "Jump opening your legs and arms while dropping into a half squat and bring them back together. A more explosive and demanding version than jumping jacks."],
[1230, "Jump onto a stable box landing with both feet and bent knees; step down. Leg power and cardiovascular work."],
[5, "From standing, drop to the floor with your chest, do a push-up, return to standing and jump with your arms up. High-intensity cardio."],
// ── Extra ──
[767, "Standing on one leg, lower in a controlled way bringing your free knee toward the floor behind you and rise without touching it down. Excellent for single-leg strength and balance."],
[1063, "Hold a band, a pole or a door frame and squat down on one leg with the other extended in front. Use just enough help to work up to the full pistol."],
[956, "Step on the band with your front foot and hold the ends at your shoulders. Lower your back knee toward the floor and rise pushing through your front heel."],
[1152, "With the dumbbells at your sides, lower until your glutes touch a bench without relaxing and rise pushing the floor away. Helps control depth."],
[906, "Lying face down on a bench with your legs hanging off, raise your legs until they line up with your torso squeezing your glutes. Lower in a controlled way."],
[1118, "On all fours, raise one leg with a 90° bent knee pushing the sole of your foot toward the ceiling. Squeeze your glute at the top and lower without resting."],
[118, "Standing with the bar at collarbone height, press up until your elbows are extended and move your head under the bar. Glutes and abs firm."],
[1183, "With a dumbbell in one hand, raise your arm out to the side to shoulder height and lower in a controlled way. The other hand holds on to avoid swinging."],
[1006, "With your forehead or chest supported on a bench, open your arms with dumbbells out to the sides with slightly bent elbows. Isolates the rear deltoid."],
[554, "Lying with a dumbbell in your hands overhead, raise your torso and legs at the same time until your feet touch the dumbbell and lower in a controlled way."],
[1156, "Standing with a dumbbell overhead, lean your torso sideways toward the floor pushing your hips back while looking at the dumbbell, and return in a controlled way."],
[1195, "Seated with your knees bent and the band anchored, rotate your torso to one side keeping your back straight and return slowly. Works the obliques."],
[1104, "In a side plank, pass your free arm under your body rotating your trunk and open it back up toward the ceiling. Works the obliques and stability."],
[1008, "In a side plank, raise the top leg without losing hip alignment and lower in a controlled way. Works the obliques and gluteus medius."],
[385, "From a forearm plank, rotate to one side raising an arm toward the ceiling, return and alternate sides with stable hips."],
[1013, "Lying down, bring your torso and knees toward the center at the same time and return without fully resting. Works the upper and lower abs together."],
[1029, "Lying with your legs raised and together, lower them to one side without touching the floor and return to the center, alternating. Arms out to stabilize."],
[98, "Walk at a brisk, steady pace with an upright torso and a natural arm swing. Low-impact cardio suitable for all levels and for recovery."],
[586, "Jump lightly alternating the support of one foot and the other with small hops and boxing arm movement. Raises your pulse with low impact."],
[351, "In a semi-bent position, move sideways with short, quick steps without crossing your feet. Improves agility and raises your heart rate."],
[639, "Jump forward with both legs swinging your arms and land softly with bent knees. Leg and glute power."],
[1065, "With the bar on your shoulders, drop into a front squat and as you rise press the bar overhead in one fluid motion. Metabolically demanding."],
[76, "Do a burpee over the dumbbells, lift them from the floor to overhead in a single movement and lower with control. Very demanding."],
[1058, "Lying on the floor, lower the bar until your elbows touch the floor and press up. Limits the range and protects your shoulders."],
[759, "Lying on the floor, press one or two kettlebells up from your chest and lower until your elbows touch the floor."],
[1198, "With the band anchored behind your back, push the ends forward until your elbows are extended and return in a controlled way. Ideal for working your chest at home."],
[1075, "With an underhand grip, lower the bar toward your lower chest with your elbows close to your body and press. Increases work for the upper chest and triceps."],
[1073, "Lying down with a close-grip EZ bar, lower the bar behind your head by bending your elbows and extend. A big stretch for the triceps."],
];
