// [índice en scratch/fp_catalogo.json, nombre ES, grupo, técnica, código sobrecarga+respiración]
module.exports = [
// ───── BRAZOS (bíceps) ─────
[251, "Curl de bíceps con mancuernas", "Brazos", "De pie con una mancuerna en cada mano y los codos pegados al torso, flexiona los codos hasta contraer el bíceps y baja controlado sin balancear el cuerpo.", "Lc"],
[259, "Curl concentrado con mancuerna", "Brazos", "Sentado con el codo apoyado en la cara interna del muslo, flexiona el codo llevando la mancuerna hacia el hombro y baja lento. Máximo aislamiento del bíceps.", "Lc"],
[270, "Curl inclinado con mancuernas", "Brazos", "Sentado en un banco inclinado a ~45° con los brazos colgando, flexiona los codos sin adelantarlos. Gran estiramiento del bíceps en la fase baja.", "Lc"],
[480, "Curl Zottman", "Brazos", "Sube las mancuernas con agarre supino, gira las muñecas arriba hasta agarre prono y baja lentamente en esa posición. Trabaja bíceps, braquial y antebrazo.", "Lc"],
[268, "Curl Scott con barra EZ", "Brazos", "Con los brazos apoyados en el banco Scott, baja la barra hasta casi extender los codos y sube sin despegar los brazos del soporte. Evita el impulso.", "Lc"],
[276, "Curl en máquina Scott", "Brazos", "Ajusta el asiento para que los brazos reposen en el soporte y flexiona los codos contra la resistencia. Controla el descenso completo.", "Lc"],
[267, "Curl Scott con mancuerna", "Brazos", "Un brazo a la vez apoyado en el banco Scott, flexiona el codo hasta contraer el bíceps y baja lento con el brazo casi extendido.", "Lc"],
[1044, "Curl con barra Z", "Brazos", "Agarra la barra Z por las curvas, codos pegados al torso, y flexiona hasta la altura del pecho. Reduce la tensión en las muñecas respecto a la barra recta.", "Lc"],
[1041, "Curl de bíceps en polea baja", "Brazos", "Frente a la polea baja con barra o agarre recto, flexiona los codos hasta contraer el bíceps y baja controlado. La polea mantiene tensión constante.", "Lc"],
[538, "Curl martillo con cuerda en polea", "Brazos", "Con la cuerda en polea baja y las palmas enfrentadas, flexiona los codos manteniéndolos pegados al cuerpo y baja controlado. Trabaja braquial y antebrazo.", "Lc"],
[292, "Curl unilateral en polea", "Brazos", "Con un solo agarre en polea baja, flexiona el codo sin mover el hombro y baja lento. Permite igualar fuerza entre ambos brazos.", "Lc"],
[479, "Curl tumbado en polea", "Brazos", "Tumbado en el suelo con los pies hacia la polea baja, flexiona los codos llevando la barra hacia la frente manteniendo los brazos quietos.", "Lc"],
[485, "Curl en polea alta (doble bíceps)", "Brazos", "De pie entre dos poleas altas, flexiona los codos llevando las manos hacia las orejas como en una pose de bíceps. Aprieta arriba y vuelve controlado.", "Lc"],
[720, "Curl inclinado en polea", "Brazos", "Sentado en banco inclinado de espaldas a la polea baja, flexiona los codos manteniendo los brazos atrás. Gran estiramiento de la cabeza larga del bíceps.", "Lc"],
[975, "Curl de bíceps con banda elástica", "Brazos", "Pisa la banda con los dos pies y flexiona los codos hasta contraer el bíceps. Controla la bajada para mantener la tensión. Opción casera y económica.", "Xc"],
[1056, "Curl martillo con banda", "Brazos", "Pisa la banda y, con las palmas enfrentadas, flexiona los codos sin despegarlos del torso. Controla el retorno.", "Xc"],
[1182, "Curl sentado alterno con mancuernas", "Brazos", "Sentado con la espalda recta, flexiona un brazo mientras el otro baja, alternando con control y rotando la muñeca hacia fuera al subir.", "Lc"],
[481, "Curl inverso con mancuernas", "Brazos", "Con agarre prono (palmas abajo), flexiona los codos manteniendo las muñecas rectas. Trabaja braquiorradial y antebrazo además del bíceps.", "Lc"],
[497, "Curl con agarre inverso y barra EZ", "Brazos", "Agarre prono sobre la barra EZ, flexiona los codos con las muñecas firmes y baja lento. Trabaja el braquial y la parte externa del antebrazo.", "Lc"],
[1123, "Curl drag con barra", "Brazos", "Sube la barra deslizándola pegada al cuerpo mientras los codos van hacia atrás. Reduce el impulso de los hombros y enfatiza el bíceps.", "Lc"],
[1149, "Curl con barra agarre cerrado", "Brazos", "Con las manos más juntas que los hombros, flexiona los codos pegados al torso hasta contraer el bíceps y baja controlado.", "Lc"],
[484, "Curl en banco inclinado boca abajo con barra", "Brazos", "Boca abajo en un banco inclinado, deja caer los brazos y flexiona los codos sin balancear. Máximo aislamiento del bíceps.", "Lc"],
[1181, "Curl martillo con botellas de agua", "Brazos", "Con una botella llena en cada mano y las palmas enfrentadas, flexiona los codos pegados al torso y baja lento. Alternativa casera sin mancuernas.", "Lc"],

// ───── TRÍCEPS ─────
[258, "Jalón de tríceps con barra en polea", "Tríceps", "De pie frente a la polea alta, con los codos pegados al torso extiende los brazos hasta bloquear abajo y vuelve controlado sin mover los hombros.", "Lc"],
[572, "Jalón de tríceps con cuerda", "Tríceps", "Con la cuerda en polea alta, extiende los codos y abre las manos al final del movimiento para contraer más el tríceps. Controla la subida.", "Lc"],
[1081, "Jalón de tríceps con agarre en V", "Tríceps", "Agarre en V en polea alta, codos pegados al cuerpo; extiende hasta abajo apretando el tríceps y sube despacio.", "Lc"],
[573, "Jalón de tríceps con agarre inverso", "Tríceps", "Con agarre supino en polea alta, extiende los codos manteniéndolos pegados al torso. Enfatiza la cabeza medial del tríceps.", "Lc"],
[72, "Jalón de tríceps a una mano", "Tríceps", "Un brazo a la vez en polea alta, con el codo fijo al costado, extiende hasta abajo y vuelve controlado. Corrige desequilibrios entre lados.", "Lc"],
[278, "Extensión de tríceps sobre la cabeza con cuerda", "Tríceps", "De espaldas a la polea y con la cuerda tras la nuca, extiende los codos sobre la cabeza manteniéndolos fijos. Gran estiramiento de la cabeza larga.", "Lc"],
[535, "Rompecráneos con mancuernas (skull crusher)", "Tríceps", "Tumbado en banco, baja las mancuernas hacia las sienes flexionando solo los codos y extiende arriba sin abrir los brazos. Mantén la parte superior de los brazos quieta.", "Lc"],
[291, "Extensión de tríceps tumbado con barra", "Tríceps", "Tumbado en banco, baja la barra hacia la frente doblando solo los codos y extiende arriba. Usa una barra EZ si las muñecas molestan.", "Lc"],
[489, "Extensión de tríceps sentado con mancuerna a dos manos", "Tríceps", "Sentado, sujeta una mancuerna con ambas manos sobre la cabeza y flexiona los codos bajándola tras la nuca. Extiende sin abrir los codos.", "Lc"],
[488, "Extensión de tríceps sentado a una mano", "Tríceps", "Sentado con una mancuerna sobre la cabeza, baja el antebrazo tras la nuca y extiende. Sujeta el codo con la otra mano para mantenerlo fijo.", "Lc"],
[539, "Extensión de tríceps sobre la cabeza con barra EZ", "Tríceps", "Sentado o de pie, baja la barra EZ tras la nuca flexionando los codos y extiende hacia arriba. Mantén el core firme y los codos cerrados.", "Lc"],
[642, "Extensión de tríceps de pie con barra", "Tríceps", "De pie con la barra sobre la cabeza, baja flexionando los codos hasta detrás de la nuca y extiende controlando. Sin arquear la espalda.", "Lc"],
[301, "Patada de tríceps en polea", "Tríceps", "Con el torso inclinado y el codo pegado al costado, extiende el brazo hacia atrás contra la polea hasta bloquear y vuelve controlado.", "Lc"],
[305, "Fondos de tríceps en el suelo", "Tríceps", "Sentado en el suelo con las manos tras la cadera y los pies apoyados, eleva la cadera extendiendo los codos y baja flexionándolos. Nivel principiante.", "Bp"],
[1040, "Flexiones diamante", "Tríceps", "Manos juntas bajo el pecho formando un diamante con índices y pulgares. Baja el pecho hacia las manos con los codos pegados al cuerpo y empuja.", "Bp"],
[33, "Press JM con barra", "Tríceps", "Híbrido entre press cerrado y extensión: baja la barra hacia la parte alta del pecho/mentón con los codos adelantados y empuja. Cargas moderadas y control.", "Lp"],
[1038, "Press de banca agarre cerrado con barra", "Tríceps", "Agarre a la anchura de los hombros, codos pegados al torso. Baja la barra al pecho bajo y empuja sin abrir los codos. Gran ejercicio de fuerza para el tríceps.", "Lp"],
[726, "Extensión de tríceps en máquina", "Tríceps", "Con los codos apoyados en el soporte, extiende los brazos hasta bloquear y vuelve controlando. Aislamiento seguro del tríceps.", "Lc"],
[728, "Fondos de tríceps en máquina", "Tríceps", "Sentado en la máquina, empuja los agarres hacia abajo extendiendo los codos pegados al cuerpo y vuelve con control.", "Lp"],
[985, "Extensión de tríceps con banda elástica", "Tríceps", "Con la banda anclada arriba, extiende los codos hacia abajo pegados al torso y vuelve controlado. Alternativa casera al jalón en polea.", "Xc"],
[976, "Rompecráneos con banda", "Tríceps", "Tumbado con la banda anclada tras la cabeza, flexiona los codos hacia la frente y extiende hacia arriba manteniendo los brazos quietos.", "Xc"],
[990, "Press Tate con mancuernas", "Tríceps", "Tumbado en banco, con las mancuernas sobre el pecho, flexiona los codos llevando las mancuernas hacia el pecho abriendo los codos y extiende. Aislamiento intenso.", "Lc"],
[1039, "Extensión de tríceps con dos mancuernas", "Tríceps", "Tumbado, con las mancuernas sobre el pecho y las palmas enfrentadas, baja controlado doblando solo los codos y extiende.", "Lc"],
[989, "Extensión de tríceps declinada con mancuernas", "Tríceps", "En banco declinado, baja las mancuernas hacia la frente y extiende los codos. El ángulo aumenta la tensión sobre el tríceps.", "Lc"],
[1080, "Rompecráneos con peso corporal", "Tríceps", "Con las manos en una barra baja o mesa estable, baja la frente flexionando los codos y extiende los brazos. Cuanto más horizontal, más difícil.", "Bp"],

// ───── ANTEBRAZOS ─────
[1042, "Curl de muñeca inverso (agarre prono)", "Antebrazos", "Antebrazos apoyados con las palmas hacia abajo, extiende las muñecas hacia arriba y baja controlado. Trabaja los extensores del antebrazo.", "Lc"],
[1142, "Curl de dedos con mancuerna", "Antebrazos", "Con el antebrazo apoyado, deja rodar la mancuerna hasta las yemas de los dedos y ciérrala de nuevo hacia la palma y flexiona la muñeca. Mejora la fuerza de agarre.", "Lc"],
[1141, "Curl de dedos con barra", "Antebrazos", "Deja que la barra ruede hasta las yemas de los dedos y vuelve a cerrarla en la palma con la muñeca flexionada. Aumenta la fuerza de agarre.", "Lc"],
[124, "Curl de muñeca con agarre neutro", "Antebrazos", "Con el antebrazo apoyado y las palmas enfrentadas, flexiona la muñeca hacia arriba con la mancuerna y baja controlado. Rango completo.", "Lc"],
[625, "Curl de muñeca detrás de la espalda con barra", "Antebrazos", "Con la barra detrás de la espalda y agarre prono, flexiona las muñecas hacia arriba y baja controlado. Recorrido corto y tensión constante.", "Lc"],
[318, "Pinza de mano (hand gripper)", "Antebrazos", "Aprieta el gripper al máximo con una sola mano y suéltalo despacio. Trabaja la fuerza de agarre y el antebrazo. Práctico para casa o gimnasio.", "Ic"],

// ───── ABDOMEN / CORE ─────
[246, "Crunch bicicleta", "Abdomen / core", "Tumbado con las manos tras la cabeza, lleva un codo hacia la rodilla contraria mientras extiendes la otra pierna, alternando lados con control y sin tirar del cuello.", "Bk"],
[245, "Escaladores (mountain climbers)", "Abdomen / core", "En posición de plancha alta, lleva las rodillas alternadas hacia el pecho a ritmo constante con la cadera estable. Trabaja core y cardio.", "Bk"],
[261, "Bicho muerto (dead bug)", "Abdomen / core", "Boca arriba con brazos y piernas elevados, baja el brazo y la pierna contrarios sin que la zona lumbar se despegue del suelo. Alterna lados.", "Bk"],
[1030, "Abdominales en V (V-up)", "Abdomen / core", "Tumbado con brazos y piernas extendidos, eleva a la vez piernas y tronco formando una V y baja controlado. Ejercicio avanzado de core.", "Bk"],
[1031, "Patada aleteo (flutter kicks)", "Abdomen / core", "Tumbado con las piernas extendidas a unos 30 cm del suelo, alterna pequeñas patadas rápidas manteniendo la zona lumbar pegada al suelo.", "Bk"],
[247, "Tijeras tumbado", "Abdomen / core", "Boca arriba con las piernas elevadas, cruza una sobre otra en movimiento de tijera manteniendo el abdomen contraído y la espalda baja pegada.", "Bk"],
[264, "Crunch inverso", "Abdomen / core", "Tumbado boca arriba con las rodillas flexionadas, eleva la pelvis del suelo llevando las rodillas hacia el pecho. Baja despacio sin balancear.", "Bk"],
[1016, "Abdominales completos (sit-ups)", "Abdomen / core", "Tumbado con las rodillas flexionadas, sube el tronco hasta sentarte con el abdomen contraído y baja controlado. Sin tirar del cuello.", "Bk"],
[262, "Abdominales en banco declinado", "Abdomen / core", "Con los pies anclados en un banco declinado, sube el tronco con el abdomen contraído y baja controlado. Mayor dificultad que en el suelo.", "Lk"],
[97, "Crunch en polea de pie", "Abdomen / core", "De pie frente a la polea alta con la cuerda en la nuca, flexiona el tronco hacia abajo contrayendo el abdomen sin mover la cadera y sube controlado.", "Lk"],
[272, "Crunch en polea de rodillas", "Abdomen / core", "De rodillas frente a la polea alta, flexiona la columna llevando los codos hacia las rodillas y vuelve despacio. Mantén la cadera quieta.", "Lk"],
[472, "Elevación de rodillas colgado", "Abdomen / core", "Colgado de una barra, sube las rodillas hacia el pecho enrollando la pelvis y baja controlado sin balancearte.", "Bk"],
[476, "Dedos a la barra (toes to bar)", "Abdomen / core", "Colgado de la barra, eleva las piernas rectas hasta tocar la barra con los pies. Exige abdomen, agarre y control. Avanzado.", "Bk"],
[475, "Limpiaparabrisas colgado", "Abdomen / core", "Colgado de la barra con las piernas elevadas, gíralas de lado a lado como un limpiaparabrisas con control. Muy exigente para los oblicuos.", "Bk"],
[508, "Plancha lateral", "Abdomen / core", "Apoyado en un antebrazo y el borde del pie, eleva la cadera para formar una línea recta de cabeza a pies y mantén la posición. Trabaja los oblicuos.", "Ii"],
[511, "Plancha con elevación de brazo y pierna", "Abdomen / core", "En plancha, eleva el brazo y la pierna contrarios y mantén 1-2 segundos sin rotar la cadera. Alterna lados.", "Ii"],
[1019, "Plancha con rodilla al codo", "Abdomen / core", "En plancha alta, lleva la rodilla hacia el codo del mismo lado y vuelve, alternando lados con la cadera estable.", "Bk"],
[20, "Plancha alta (brazos extendidos)", "Abdomen / core", "Con las manos bajo los hombros y el cuerpo recto de cabeza a talones, aprieta glúteos y abdomen y mantén la posición. Respira de forma constante.", "Ii"],
[390, "Elevación de piernas en silla romana", "Abdomen / core", "Apoyado en los antebrazos en la silla romana, sube las piernas rectas o flexionadas hasta la horizontal sin balancear y baja con control.", "Bk"],
[387, "Inclinación lateral con mancuerna", "Abdomen / core", "De pie con una mancuerna en una mano, inclina el torso hacia ese lado y vuelve contrayendo el oblicuo contrario. Sin inclinarte hacia delante.", "Lk"],
[528, "Inclinación lateral en polea", "Abdomen / core", "De pie junto a la polea baja, inclina el torso en dirección contraria a la polea y vuelve controlado. Mantén la cadera quieta.", "Lk"],
[926, "Press Pallof en polea", "Abdomen / core", "De lado a la polea, empuja el agarre al frente y aguanta 1-2 segundos resistiendo la rotación. Trabaja el core antirrotación.", "Ik"],
[608, "Crunch en máquina", "Abdomen / core", "Sentado en la máquina, flexiona el tronco contrayendo el abdomen y vuelve controlado. Ajusta el peso para mantener la técnica.", "Lk"],
[574, "Leñador en polea (alto a bajo)", "Abdomen / core", "De pie junto a la polea alta, tira diagonalmente hacia la cadera contraria rotando el torso y controla el retorno. Trabaja oblicuos.", "Lk"],
[575, "Leñador en polea (bajo a alto)", "Abdomen / core", "De pie junto a la polea baja, tira en diagonal hacia arriba por encima del hombro contrario rotando el tronco y vuelve despacio.", "Lk"],
[581, "L-sit (sostén en L)", "Abdomen / core", "Apoyado en las manos sobre barras o suelo, eleva el cuerpo con las piernas extendidas al frente formando una L y mantén. Exigente para abdomen y tríceps.", "Ii"],
[19, "Gateo de oso (bear crawl)", "Abdomen / core", "En cuadrupedia con las rodillas a unos centímetros del suelo, avanza moviendo mano y pie contrarios con la espalda plana. Core y hombros en acción.", "Bk"],
[254, "Crunch oblicuo en el suelo", "Abdomen / core", "Tumbado con las rodillas flexionadas hacia un lado, eleva el torso y lleva el hombro hacia la rodilla contraria. Alterna lados.", "Bk"],
[15, "Vacío abdominal de pie", "Abdomen / core", "De pie, exhala todo el aire y contrae el abdomen metiéndolo hacia dentro y arriba. Mantén 15-20 segundos sin inhalar. Fortalece el transverso del abdomen.", "Ii"],
[407, "Plancha inversa", "Abdomen / core", "Sentado con las manos tras la cadera, eleva la pelvis y alinea cuerpo y piernas mirando al techo. Trabaja glúteos, lumbares y core posterior.", "Ii"],
[14, "Plancha sierra (body saw)", "Abdomen / core", "En plancha sobre antebrazos con los pies sobre toallas o discos deslizantes, balancea el cuerpo hacia delante y atrás sin arquear la espalda.", "Bk"],
[96, "Crunch cruzado", "Abdomen / core", "Tumbado con las manos en la nuca, lleva un codo hacia la rodilla contraria con rotación de tronco controlada y alterna lados.", "Bk"],
[273, "Toques de talón (heel touch)", "Abdomen / core", "Tumbado con las rodillas flexionadas, eleva ligeramente los hombros y toca alternadamente cada talón con la mano del mismo lado. Trabaja oblicuos.", "Bk"],

// ───── CARDIO / ACONDICIONAMIENTO ─────
[106, "Correr (carrera continua)", "Cardio / acondicionamiento", "Mantén un ritmo constante conversable, con el torso erguido y el apoyo del pie bajo el cuerpo. Aumenta gradualmente tiempo o distancia.", "Rr"],
[133, "Cinta de correr", "Cardio / acondicionamiento", "Camina o corre a velocidad controlada manteniendo la postura erguida y sin agarrarte a las barras. Ajusta velocidad e inclinación según tu objetivo.", "Rr"],
[134, "Caminata en cinta inclinada", "Cardio / acondicionamiento", "Camina a paso firme en cinta con 8-12% de inclinación sin apoyarte en las barras. Alta quema calórica con bajo impacto.", "Rr"],
[132, "Bicicleta estática", "Cardio / acondicionamiento", "Ajusta el sillín para que la rodilla quede casi extendida abajo y pedalea con cadencia constante. Ideal para cardio de bajo impacto.", "Rr"],
[135, "Ergómetro de remo (cardio)", "Cardio / acondicionamiento", "Empuja con las piernas, inclina el torso y tira del agarre hacia el abdomen; vuelve en orden inverso. Cardio completo que involucra todo el cuerpo.", "Rr"],
[137, "Elíptica", "Cardio / acondicionamiento", "Mantén el torso erguido y empuja los pedales con movimiento fluido, usando también los agarres móviles. Cardio de muy bajo impacto articular.", "Rr"],
[138, "Escaladora (stair climber)", "Cardio / acondicionamiento", "Sube los escalones con el torso erguido y sin apoyar todo el peso en las barras. Gran trabajo de piernas y glúteos con cardio intenso.", "Rr"],
[107, "Sprints", "Cardio / acondicionamiento", "Corre a máxima velocidad durante 10-30 segundos con pausas completas entre series. Calienta bien antes y mantén buena técnica.", "Rr"],
[401, "Carrera en el sitio", "Cardio / acondicionamiento", "Corre sin desplazarte elevando bien las rodillas y moviendo los brazos. Ideal como calentamiento o cardio en casa sin material.", "Rr"],
[402, "Sentadillas con salto", "Cardio / acondicionamiento", "Baja a sentadilla y salta explosivamente extendiendo caderas y rodillas. Aterriza suave con las rodillas flexionadas y repite.", "Rr"],
[580, "Salto de rodillas al pecho (tuck jump)", "Cardio / acondicionamiento", "Salta verticalmente llevando las rodillas hacia el pecho en el aire y aterriza suave. Alta intensidad; hazlo con técnica y descansa entre series.", "Rr"],
[325, "Talones al glúteo (butt kicks)", "Cardio / acondicionamiento", "Trotando en el sitio, lleva los talones hacia los glúteos de forma alterna con el torso erguido. Buen calentamiento para isquiotibiales.", "Rr"],
[1011, "Rodillas altas (high knees)", "Cardio / acondicionamiento", "Corre en el sitio elevando las rodillas hasta la altura de la cadera con los brazos activos. Intensifica el ritmo cardíaco rápidamente.", "Rr"],
[1022, "Patinador (skater)", "Cardio / acondicionamiento", "Salta lateralmente de una pierna a la otra como un patinador, cruzando la pierna libre por detrás. Trabaja glúteos y cardio.", "Rr"],
[55, "Boxeo de sombra", "Cardio / acondicionamiento", "Lanza golpes al aire con movimientos de pies y rotación de cadera y hombros, manteniendo la guardia. Cardio, coordinación y diversión.", "Rr"],
[603, "Swing con kettlebell", "Cardio / acondicionamiento", "Con la kettlebell entre las piernas, impulsa la cadera hacia delante para subirla a la altura del pecho con los brazos relajados. El movimiento sale de la cadera, no de los brazos.", "Rs"],
[697, "Burpee con mancuernas", "Cardio / acondicionamiento", "Realiza el burpee sujetando mancuernas: pecho al suelo, sube y salta. Aumenta la exigencia metabólica; usa cargas ligeras y buena técnica.", "Rr"],
[503, "Levantamiento turco (Turkish get-up)", "Cardio / acondicionamiento", "Tumbado con una kettlebell o mancuerna en el brazo extendido, ponte de pie en etapas controladas y vuelve al suelo. Fuerza total, estabilidad y movilidad.", "Lk"],
[1175, "Bicicleta de aire (assault bike)", "Cardio / acondicionamiento", "Pedalea y empuja y tira de las palancas a la vez; cuanto más fuerte, más resistencia. Perfecta para intervalos de alta intensidad.", "Rr"],
[322, "Saltos de apertura pliométricos", "Cardio / acondicionamiento", "Salta abriendo piernas y brazos bajando a media sentadilla y vuelve a juntar. Versión más explosiva y con mayor exigencia que los saltos de tijera.", "Rr"],
[1230, "Salto al cajón (box jump)", "Cardio / acondicionamiento", "Salta sobre un cajón estable aterrizando con ambos pies y las rodillas flexionadas; baja caminando. Potencia de piernas y trabajo cardiovascular.", "Rr"],
[5, "Burpee con flexión", "Cardio / acondicionamiento", "Desde de pie, baja al suelo con el pecho, haz una flexión, vuelve a de pie y salta con los brazos arriba. Cardio de alta intensidad.", "Rr"],
];
