// [índice en scratch/fp_catalogo.json, nombre ES, grupo, técnica, código sobrecarga+respiración]
module.exports = [
[767, "Sentadilla patinador", "Piernas", "De pie sobre una pierna, baja controlado llevando la rodilla libre hacia el suelo por detrás y sube sin apoyarla. Excelente para fuerza unilateral y equilibrio.", "Bs"],
[1063, "Pistol asistida (con apoyo)", "Piernas", "Sujeta una banda, una columna o el marco de una puerta y baja en sentadilla a una pierna con la otra extendida al frente. Usa la ayuda justa para llegar a la pistola completa.", "Bs"],
[956, "Sentadilla dividida con banda", "Piernas", "Pisa la banda con el pie delantero y sujeta los extremos a los hombros. Baja la rodilla trasera hacia el suelo y sube empujando con el talón delantero.", "Xs"],
[1152, "Sentadilla en banco con mancuernas", "Piernas", "Con las mancuernas a los lados, baja hasta tocar un banco con los glúteos sin relajarte y sube empujando el suelo. Ayuda a controlar la profundidad.", "Ls"],
[906, "Extensión de cadera en banco", "Piernas", "Tumbado boca abajo sobre un banco con las piernas fuera, eleva las piernas hasta alinearlas con el tronco apretando glúteos. Baja controlado.", "Bs"],
[1118, "Patada de glúteo con rodilla flexionada", "Piernas", "En cuadrupedia, eleva una pierna con la rodilla flexionada a 90° empujando la planta del pie hacia el techo. Aprieta el glúteo arriba y baja sin apoyar.", "Bs"],
[118, "Press militar de pie con barra", "Hombros", "De pie con la barra a la altura de la clavícula, empuja hacia arriba hasta extender los codos y pasa la cabeza por debajo de la barra. Glúteos y abdomen firmes.", "Lp"],
[1183, "Elevación lateral a una mano con mancuerna", "Hombros", "Con una mancuerna en una mano, eleva el brazo lateralmente hasta la altura del hombro y baja controlado. La otra mano se apoya para evitar balancear.", "Lc"],
[1006, "Pájaros con el pecho apoyado en banco", "Hombros", "Con la frente o el pecho apoyados en un banco, abre los brazos con mancuernas hacia los lados con los codos semiflexionados. Aísla el deltoides posterior.", "Lc"],
[554, "Abdominales en V con mancuerna", "Abdomen / core", "Tumbado con una mancuerna en las manos sobre la cabeza, sube a la vez tronco y piernas hasta tocar la mancuerna con los pies y baja controlado.", "Lk"],
[1156, "Molino con mancuerna (windmill)", "Abdomen / core", "De pie con una mancuerna sobre la cabeza, inclina el torso lateralmente hacia el suelo llevando la cadera hacia atrás, mirando la mancuerna, y vuelve controlado.", "Lk"],
[1195, "Giro sentado con banda", "Abdomen / core", "Sentado con las piernas flexionadas y la banda anclada, rota el torso hacia un lado manteniendo la espalda recta y vuelve despacio. Trabaja los oblicuos.", "Xk"],
[1104, "Side plank con rotación", "Abdomen / core", "En plancha lateral, pasa el brazo libre bajo el cuerpo rotando el tronco y vuelve a abrirlo hacia el techo. Trabaja oblicuos y estabilidad.", "Bk"],
[1008, "Side plank con elevación de pierna", "Abdomen / core", "En plancha lateral, eleva la pierna de arriba sin perder la alineación de la cadera y baja controlado. Trabaja oblicuos y glúteo medio.", "Bk"],
[385, "Plancha frontal a side plank", "Abdomen / core", "Desde plancha sobre antebrazos, rota hacia un lado elevando un brazo al techo, vuelve y alterna lados con la cadera estable.", "Bk"],
[1013, "Crunch doble", "Abdomen / core", "Tumbado, lleva a la vez el torso y las rodillas hacia el centro y vuelve sin apoyar del todo. Trabaja la parte alta y baja del abdomen juntas.", "Bk"],
[1029, "Limpiaparabrisas en el suelo (medios)", "Abdomen / core", "Tumbado con las piernas elevadas y juntas, bájalas hacia un lado sin tocar el suelo y vuelve al centro, alternando. Brazos abiertos para estabilizarte.", "Bk"],
[98, "Caminata ligera", "Cardio / acondicionamiento", "Camina a paso ligero y constante con el torso erguido y los brazos en movimiento natural. Cardio de bajo impacto apto para todos los niveles y para recuperar.", "Rr"],
[586, "Salto de boxeador (boxer shuffle)", "Cardio / acondicionamiento", "Salta de forma ligera alternando el apoyo de un pie y otro con pequeños saltos y movimiento de brazos tipo boxeo. Eleva el pulso con poco impacto.", "Rr"],
[351, "Pasos laterales rápidos", "Cardio / acondicionamiento", "En posición semiflexionada, desplázate lateralmente con pasos cortos y rápidos sin cruzar los pies. Mejora la agilidad y eleva las pulsaciones.", "Rr"],
[639, "Salto de longitud", "Cardio / acondicionamiento", "Salta hacia delante con las dos piernas balanceando los brazos y aterriza suave con las rodillas flexionadas. Potencia de piernas y glúteos.", "Rr"],
[1065, "Thruster con barra", "Cardio / acondicionamiento", "Con la barra en los hombros, baja en sentadilla frontal y al subir empuja la barra sobre la cabeza en un solo movimiento fluido. Exigente a nivel metabólico.", "Ls"],
[76, "Devil press con mancuernas", "Cardio / acondicionamiento", "Haz un burpee sobre las mancuernas, súbelas del suelo hasta pasarlas por encima de la cabeza en un solo movimiento y baja con control. Muy exigente.", "Ls"],
[1058, "Press de suelo con barra", "Pecho", "Tumbado en el suelo, baja la barra hasta que los codos toquen el suelo y empuja hacia arriba. Limita el recorrido y protege los hombros.", "Lp"],
[759, "Press de pecho en el suelo con kettlebell", "Pecho", "Tumbado en el suelo, empuja una o dos kettlebells hacia arriba desde el pecho y baja hasta que los codos toquen el suelo.", "Lp"],
[1198, "Press de pecho de pie con banda", "Pecho", "Con la banda anclada a la espalda, empuja los extremos hacia delante hasta extender los codos y vuelve controlando. Ideal para trabajar el pecho en casa.", "Xp"],
[1075, "Press de banca agarre inverso", "Tríceps", "Con agarre supino, baja la barra hacia la parte baja del pecho con los codos cerca del cuerpo y empuja. Aumenta el trabajo del pecho superior y del tríceps.", "Lp"],
[1073, "Extensión de tríceps tumbado tras la cabeza con barra EZ", "Tríceps", "Tumbado con la barra EZ de agarre cerrado, baja la barra por detrás de la cabeza flexionando los codos y extiende. Gran estiramiento del tríceps.", "Lc"],
];
