// [índice en scratch/fp_catalogo.json, nombre ES, grupo, técnica, código sobrecarga+respiración]
module.exports = [
// ───── PECHO ─────
[288, "Press de banca plano con mancuernas", "Pecho", "Acostado en banco plano, baja las mancuernas a la altura del pecho con los codos a ~60-75° del tronco y empuja hacia arriba juntándolas sin chocar. Escápulas retraídas y pies firmes en el suelo.", "Lp"],
[311, "Press de banca declinado con mancuernas", "Pecho", "En banco declinado, baja las mancuernas hacia la parte baja del pecho de forma controlada y empuja en línea vertical. Mantén las muñecas rectas y los codos a ~60° del tronco.", "Lp"],
[295, "Aperturas inclinadas con mancuernas", "Pecho", "Banco a 30°. Con los codos ligeramente flexionados, abre los brazos en arco hasta notar el estiramiento del pecho y vuelve juntando las mancuernas arriba sin chocarlas.", "Lc"],
[283, "Aperturas en polea baja (cruce ascendente)", "Pecho", "Poleas a la altura de los tobillos y torso ligeramente inclinado. Sube los brazos en arco hasta juntar las manos a la altura del pecho, apretando el pectoral superior.", "Lc"],
[284, "Aperturas en polea alta (cruce descendente)", "Pecho", "Poleas arriba, un pie adelantado para estabilizar. Lleva las manos en arco hacia abajo y adelante hasta juntarlas frente al abdomen, con codos semiflexionados.", "Lc"],
[281, "Contractora de pecho (pec deck)", "Pecho", "Siéntate con la espalda pegada al respaldo y los codos a la altura del pecho. Junta los brazos al frente apretando el pecho y vuelve controlando el estiramiento sin despegar la espalda.", "Lc"],
[1053, "Press de pecho en máquina", "Pecho", "Ajusta el asiento para que los agarres queden a la altura del pecho medio. Empuja sin bloquear los codos y vuelve controlando 2-3 segundos, con la espalda apoyada.", "Lp"],
[315, "Press de pecho inclinado en máquina", "Pecho", "Con el respaldo fijo y los agarres a la altura de la parte alta del pecho, empuja hacia arriba y adelante sin encoger los hombros. Controla el retorno.", "Lp"],
[761, "Press de banca agarre ancho con barra", "Pecho", "Agarra la barra más ancha que los hombros y baja hasta rozar el pecho con los codos más abiertos. Pone mayor énfasis en el pectoral exterior; no rebotes la barra.", "Lp"],
[762, "Press de banca declinado con barra", "Pecho", "En banco declinado, baja la barra a la parte baja del pecho y empuja en línea recta. Usa soportes o un compañero para sacar y devolver la barra de forma segura.", "Lp"],
[552, "Flexiones inclinadas (manos elevadas)", "Pecho", "Apoya las manos en un banco, silla o escalón estable y mantén el cuerpo en línea recta. Baja el pecho hacia el apoyo y empuja. Es la versión más fácil de la flexión.", "Bp"],
[478, "Flexiones de rodillas", "Pecho", "Apoya las rodillas en el suelo, cuerpo recto de rodillas a cabeza y manos bajo los hombros. Baja el pecho casi hasta el suelo y empuja sin arquear la zona lumbar.", "Bp"],
[1231, "Flexiones declinadas (pies elevados)", "Pecho", "Con los pies sobre un banco o silla y las manos en el suelo, baja el pecho de forma controlada y empuja. Enfatiza el pecho superior y los hombros; mantén el core firme.", "Bp"],
[593, "Flexiones con palmada", "Pecho", "Baja el pecho al suelo y empuja con tanta fuerza que las manos se despeguen para dar una palmada. Aterriza con los codos ligeramente flexionados. Ejercicio explosivo para nivel avanzado.", "Bp"],
[1132, "Flexiones arquero", "Pecho", "Con las manos muy separadas, baja el cuerpo hacia una mano mientras el brazo contrario se mantiene extendido y alterna lados. Trabaja el pecho de forma unilateral.", "Bp"],
[1166, "Flexiones con toque de hombro", "Pecho", "En posición de flexión, baja y sube y, arriba, toca un hombro con la mano contraria sin girar la cadera. Combina pecho y estabilidad del core.", "Bp"],
[1052, "Press martillo con mancuernas (agarre neutro)", "Pecho", "Acostado en banco, con las palmas enfrentadas, empuja las mancuernas hacia arriba manteniendo los codos pegados al cuerpo. Reduce la tensión en los hombros.", "Lp"],
[924, "Press de pecho sentado en polea", "Pecho", "Sentado con la espalda apoyada, empuja los agarres de polea al frente hasta casi extender los codos y vuelve controlando. La tensión constante de la polea mantiene el pecho activo.", "Lp"],
[290, "Press de pecho unilateral en polea", "Pecho", "De pie y de lado a la polea, empuja un solo agarre al frente sin rotar el torso. Trabaja el pecho y el core antirrotación; repite en ambos lados.", "Lp"],
[840, "Aperturas inclinadas en polea", "Pecho", "Banco inclinado entre dos poleas bajas. Abre los brazos en arco con los codos semiflexionados y júntalos sobre la parte alta del pecho apretando.", "Lc"],
[1136, "Aperturas con banda elástica", "Pecho", "Banda anclada a la espalda o a un punto fijo. Con los codos ligeramente flexionados, junta las manos al frente en arco apretando el pecho y vuelve controlando.", "Xc"],
[1126, "Flexiones hindúes", "Pecho", "Desde posición de V invertida, baja el pecho en arco hacia el suelo y sube a una cobra empujando con los brazos; invierte el movimiento. Combina pecho, hombros y movilidad.", "Bp"],

// ───── ESPALDA ─────
[712, "Dominadas supinas (chin-up)", "Espalda", "Agarre supino a la anchura de los hombros. Sube hasta pasar la barbilla de la barra llevando los codos hacia las caderas y baja sin balancearte. Mayor participación del bíceps.", "Bt"],
[1100, "Dominadas con agarre neutro", "Espalda", "Con los agarres paralelos, sube hasta pasar la barbilla y baja completamente. Es una posición cómoda para hombros y codos, con gran trabajo del dorsal.", "Bt"],
[454, "Dominadas asistidas en máquina", "Espalda", "Elige un contrapeso que te permita completar las repeticiones con buena técnica. Sube llevando el pecho a la barra y baja controlado; reduce la asistencia progresivamente.", "Lt"],
[1155, "Dominadas asistidas con banda", "Espalda", "Pasa una banda elástica por la barra y apoya rodillas o pies en ella. Sube con el pecho hacia la barra y baja controlado; usa bandas más finas al progresar.", "Xt"],
[509, "Jalón con agarre en V (triángulo)", "Espalda", "Siéntate con el torso ligeramente inclinado hacia atrás y tira del agarre en V hacia el pecho, juntando las escápulas. Vuelve estirando por completo sin soltar la tensión.", "Lt"],
[618, "Jalón con agarre estrecho", "Espalda", "Agarre cerrado y neutro, tira hacia la parte alta del pecho llevando los codos pegados al cuerpo. Enfatiza la zona baja del dorsal.", "Lt"],
[230, "Jalón con brazos rectos en polea", "Espalda", "De pie frente a la polea alta, con brazos casi rectos baja la barra hasta los muslos contrayendo el dorsal. Sin flexionar los codos ni usar el impulso del torso.", "Lt"],
[490, "Jalón unilateral en polea", "Espalda", "Con una mano en el agarre, tira hacia el hombro llevando el codo hacia la cadera. Permite mayor rango de movimiento y corregir desequilibrios entre lados.", "Lt"],
[224, "Jalón frontal en máquina", "Espalda", "Ajusta el rodillo de los muslos y tira de los agarres hasta la parte alta del pecho con el pecho erguido. Vuelve controlando hasta estirar los brazos.", "Lt"],
[240, "Remo en máquina sentado", "Espalda", "Con el pecho apoyado, tira de los agarres hacia el abdomen juntando las escápulas y vuelve estirando sin despegar el torso del soporte.", "Lt"],
[506, "Remo en polea con agarre cerrado", "Espalda", "Sentado con la espalda recta, tira del agarre en V hacia el abdomen bajo, junta las escápulas y vuelve estirando sin redondear la zona lumbar.", "Lt"],
[619, "Remo en polea con cuerda", "Espalda", "Tira de la cuerda hacia el pecho abriendo ligeramente las manos al final del movimiento. Mantén el pecho alto y los codos cerca del cuerpo.", "Lt"],
[241, "Remo unilateral en polea", "Espalda", "De pie o sentado, tira de un solo agarre hacia la cadera sin rotar el torso. Permite un buen recorrido y corregir desequilibrios entre lados.", "Lt"],
[242, "Remo supino con barra (agarre invertido)", "Espalda", "Con el torso inclinado ~45° y la espalda recta, tira de la barra con agarre supino hacia el abdomen. Mayor trabajo del dorsal inferior y del bíceps.", "Lt"],
[994, "Remo Pendlay (barra desde el suelo)", "Espalda", "Torso paralelo al suelo. Tira de la barra desde el suelo explosivamente hacia el abdomen y devuélvela al suelo en cada repetición, con la espalda neutra.", "Lt"],
[540, "Remo apoyado en banco inclinado con barra", "Espalda", "Con el pecho apoyado en un banco inclinado, tira de la barra hacia el abdomen sin impulso. Elimina el balanceo y protege la zona lumbar.", "Lt"],
[235, "Remo a dos manos con mancuernas (inclinado)", "Espalda", "Inclina el torso con la espalda recta y tira de las dos mancuernas hacia las caderas, juntando las escápulas. Baja controlando hasta estirar los brazos.", "Lt"],
[443, "Remo supino con mancuernas en banco inclinado", "Espalda", "Tumbado boca abajo en un banco inclinado, tira de las mancuernas con agarre supino hacia las costillas. Sin impulso desde las piernas.", "Lt"],
[1110, "Remo tumbado en banco con mancuernas", "Espalda", "Acostado boca abajo en un banco alto, tira de las mancuernas hacia las costillas y baja controlado. Aísla la espalda sin carga en la zona lumbar.", "Lt"],
[695, "Remo con kettlebell", "Espalda", "Torso inclinado con la espalda neutra y la kettlebell colgando; tira hacia la cadera llevando el codo atrás y baja con control. Alterna brazos.", "Lt"],
[466, "Remo invertido en mesa", "Espalda", "Acostado bajo una mesa robusta, agarra el borde y tira del pecho hacia ella con el cuerpo recto. Excelente opción casera para la espalda.", "Bt"],
[644, "Remo invertido en barra baja", "Espalda", "Bajo una barra a la altura de la cadera, tira del pecho hacia la barra con el cuerpo en línea recta. Cuanto más horizontal, más difícil.", "Bt"],
[984, "Remo sentado con banda", "Espalda", "Sentado con las piernas extendidas y la banda en los pies, tira de los extremos hacia el abdomen juntando las escápulas y vuelve controlando.", "Xt"],
[1190, "Remo de pie con banda", "Espalda", "Banda anclada a la altura del pecho; tira de los extremos hacia el torso con los codos pegados y la espalda recta. Vuelve despacio.", "Xt"],
[249, "Peso muerto convencional", "Espalda", "Barra sobre el medio del pie, agarre a la anchura de los hombros, espalda neutra y pecho alto. Empuja el suelo con las piernas y extiende la cadera sin redondear la espalda.", "Ls"],
[991, "Rack pull (peso muerto desde soportes)", "Espalda", "Barra en soportes a la altura de la rodilla. Extiende cadera y rodillas manteniendo la espalda recta y aprieta glúteos y dorsales arriba. Permite cargar más en la parte alta de la espalda.", "Ls"],
[800, "Dominadas escapulares", "Espalda", "Colgado de la barra con los brazos rectos, eleva el cuerpo solo moviendo las escápulas hacia abajo y atrás, sin doblar los codos. Mejora el control del hombro y el dorsal.", "Bt"],
[996, "Superman", "Espalda", "Tumbado boca abajo, eleva a la vez brazos y piernas del suelo apretando glúteos y lumbares. Mantén 1-2 segundos arriba y baja con control.", "Ik"],
[614, "Bird dog (perro-pájaro)", "Espalda", "En cuadrupedia, extiende el brazo y la pierna contrarios manteniendo la espalda neutra y la cadera quieta. Alterna lados con control.", "Ik"],
[468, "Hiperextensión inversa en máquina", "Espalda", "Apoyado en la máquina boca abajo, eleva las piernas hasta alinearlas con el torso apretando glúteos y lumbares. Sin balancear con impulso.", "Ls"],
[312, "Buenos días con barra", "Espalda", "Barra en la parte alta de la espalda, rodillas ligeramente flexionadas. Inclina el torso hacia delante llevando la cadera atrás con la espalda recta y vuelve apretando glúteos.", "Ls"],
[50, "Buenos días con mancuerna", "Espalda", "Sostén una mancuerna contra el pecho o los hombros. Lleva la cadera atrás inclinando el torso con la espalda neutra y vuelve extendiendo la cadera.", "Ls"],
];
