// [índice en scratch/fp_catalogo.json, nombre ES, grupo, técnica, código sobrecarga+respiración]
module.exports = [
// ───── PIERNAS (incluye glúteos y gemelos) ─────
[744, "Sentadilla frontal con barra", "Piernas", "Barra apoyada en la parte delantera de los hombros con los codos altos. Baja con el torso erguido hasta la paralela o más y empuja el suelo para subir. Mayor énfasis en cuádriceps.", "Ls"],
[317, "Sentadilla hack en máquina", "Piernas", "Espalda apoyada en el respaldo y pies al ancho de hombros. Baja hasta que los muslos queden paralelos o más y empuja sin bloquear las rodillas arriba.", "Ls"],
[338, "Zancada con barra", "Piernas", "Barra en la parte alta de la espalda, da un paso largo y baja hasta que ambas rodillas formen ~90°. Empuja con el talón delantero para volver. Alterna piernas.", "Ls"],
[914, "Hip thrust en máquina", "Piernas", "Espalda alta apoyada y pies firmes en la plataforma. Empuja la cadera hacia arriba apretando los glúteos y baja controlado sin perder la tensión.", "Ls"],
[364, "Patada de glúteo en máquina", "Piernas", "Apoya el pecho y empuja la plataforma hacia atrás con el talón, extendiendo la cadera y apretando el glúteo. Vuelve controlando sin arquear la zona lumbar.", "Lc"],
[1050, "Abducción de cadera en máquina", "Piernas", "Sentado con la espalda apoyada, abre las piernas contra las almohadillas y vuelve despacio. Trabaja el glúteo medio y la parte externa de la cadera.", "Lc"],
[1049, "Aducción de cadera en máquina", "Piernas", "Sentado, junta las piernas contra las almohadillas apretando la parte interna del muslo y vuelve controlando el recorrido.", "Lc"],
[742, "Peso muerto con barra hexagonal (trap bar)", "Piernas", "Dentro de la barra hexagonal, espalda neutra y pecho alto. Empuja el suelo con las piernas hasta quedar erguido y baja con control. Postura más amigable para la espalda.", "Ls"],
[316, "Rumano con mancuernas", "Piernas", "Con las mancuernas frente a los muslos, lleva la cadera atrás con las rodillas ligeramente flexionadas hasta sentir el estiramiento del isquio. Sube apretando glúteos.", "Ls"],
[810, "Peso muerto con piernas rígidas", "Piernas", "Con las rodillas casi extendidas, baja la barra pegada a las piernas inclinando el torso con la espalda recta. Gran estiramiento de isquiotibiales; sube extendiendo la cadera.", "Ls"],
[1147, "Peso muerto a una pierna con mancuerna", "Piernas", "De pie sobre una pierna, inclina el torso llevando la mancuerna hacia el suelo mientras la otra pierna se eleva atrás. Cadera cuadrada y espalda neutra.", "Ls"],
[606, "Peso muerto a una pierna con peso corporal", "Piernas", "Apoyado en una pierna, inclina el torso hacia delante elevando la otra pierna atrás y los brazos hacia el suelo. Cadera alineada. Mejora equilibrio e isquiotibiales.", "Bs"],
[38, "Sentadilla goblet con mancuerna", "Piernas", "Sostén una mancuerna contra el pecho, pies al ancho de hombros. Baja entre las rodillas con el torso erguido y sube empujando el suelo. Ideal para aprender la sentadilla.", "Ls"],
[345, "Sentadilla con peso corporal", "Piernas", "Pies al ancho de hombros, baja la cadera atrás y abajo con la espalda recta y las rodillas alineadas con los pies. Sube empujando el suelo. Base de todo entrenamiento en casa.", "Bs"],
[331, "Sentadilla sumo con peso corporal", "Piernas", "Pies más anchos que los hombros y puntas hacia fuera. Baja con el torso erguido y rodillas siguiendo la línea de los pies. Trabaja aductores y glúteos.", "Bs"],
[1048, "Sentadilla sumo con mancuerna", "Piernas", "Pies anchos y puntas abiertas, mancuerna colgando entre las piernas. Baja manteniendo el pecho alto y sube apretando glúteos y aductores.", "Ls"],
[36, "Sentadilla cosaca con mancuerna", "Piernas", "Con los pies muy separados, desplaza el peso hacia un lado flexionando esa rodilla mientras la otra pierna queda extendida. Sube y alterna. Trabaja aductores y glúteos.", "Ls"],
[59, "Zancada con peso corporal", "Piernas", "Da un paso largo al frente y baja hasta que ambas rodillas formen ~90° con el torso erguido. Empuja con el talón delantero para volver. Alterna piernas.", "Bs"],
[621, "Zancada hacia atrás", "Piernas", "Da un paso largo atrás y baja la rodilla trasera hacia el suelo con el torso erguido. Menos estrés en la rodilla que la zancada frontal.", "Bs"],
[1033, "Estocada inversa con mancuernas", "Piernas", "Con una mancuerna en cada mano, retrocede y baja hasta ~90° en ambas rodillas, manteniendo el tronco firme. Empuja con el pie delantero para volver.", "Ls"],
[328, "Zancada con mancuernas", "Piernas", "Mancuernas a los lados, paso largo al frente y baja controlado hasta que las rodillas formen ~90°. Empuja con el talón delantero para volver.", "Ls"],
[47, "Zancadas caminando con mancuernas", "Piernas", "Avanza alternando piernas con una mancuerna en cada mano, bajando la rodilla trasera cerca del suelo en cada paso. Mantén el torso erguido.", "Ls"],
[570, "Zancadas caminando con peso corporal", "Piernas", "Avanza alternando piernas, bajando la rodilla trasera hacia el suelo en cada paso y empujando con la pierna delantera. Torso recto y pasos amplios.", "Bs"],
[341, "Zancada lateral", "Piernas", "Da un paso amplio al lado y flexiona esa rodilla llevando la cadera atrás mientras la otra pierna queda extendida. Empuja para volver. Trabaja aductores y glúteos.", "Bs"],
[39, "Zancada cruzada (curtsy)", "Piernas", "Lleva una pierna atrás y en diagonal cruzando por detrás de la otra y baja hasta ~90°. Vuelve a la posición inicial. Trabaja glúteo medio y cuádriceps.", "Bs"],
[505, "Hip thrust con peso corporal", "Piernas", "Con la espalda alta apoyada en un banco o sofá, empuja la cadera hacia arriba hasta alinearla con el tronco, apretando glúteos 1-2 segundos arriba. Baja controlado.", "Bs"],
[1025, "Puente de glúteos", "Piernas", "Tumbado boca arriba con rodillas flexionadas, eleva la cadera apretando los glúteos hasta formar una línea hombros-rodillas. Baja despacio. Ideal para activar el glúteo.", "Bs"],
[635, "Elevación de cadera con mancuerna", "Piernas", "Con una mancuerna sobre la cadera, eleva la pelvis apretando los glúteos hasta alinear tronco y muslos. Baja controlado sin apoyar del todo.", "Ls"],
[525, "Elevación de cadera a una pierna", "Piernas", "Con una pierna extendida en el aire, eleva la cadera con la otra apretando el glúteo. Mantén la pelvis nivelada y baja controlado.", "Bs"],
[938, "Elevación de cadera con banda", "Piernas", "Banda sobre los muslos, justo encima de las rodillas. Eleva la cadera empujando las rodillas hacia fuera contra la banda para sumar glúteo medio.", "Xs"],
[946, "Caminata lateral con banda elástica", "Piernas", "Banda alrededor de los muslos o tobillos, con rodillas ligeramente flexionadas. Da pasos laterales amplios manteniendo la tensión en la banda y la cadera nivelada.", "Xs"],
[949, "Patada de glúteo con banda", "Piernas", "En cuadrupedia con la banda en los pies o sobre las rodillas, extiende una pierna hacia atrás apretando el glúteo sin arquear la espalda.", "Xs"],
[953, "Fire hydrant con banda", "Piernas", "En cuadrupedia con la banda sobre las rodillas, abre una rodilla hacia el lateral contra la banda manteniendo la pelvis estable. Trabaja el glúteo medio.", "Xs"],
[997, "Fire hydrant (apertura de cadera en cuadrupedia)", "Piernas", "En cuadrupedia, eleva una rodilla lateralmente manteniendo el ángulo de 90° y la pelvis estable. Baja controlado y repite en ambos lados.", "Bs"],
[1005, "Patada de burro (donkey kick)", "Piernas", "En cuadrupedia, empuja el talón hacia el techo con la rodilla flexionada hasta alinear el muslo con la espalda, apretando el glúteo. Baja sin apoyar.", "Bs"],
[347, "Almeja (clamshell) en el suelo", "Piernas", "Tumbado de lado con las rodillas flexionadas y los pies juntos, abre la rodilla superior sin mover la pelvis y vuelve. Activa el glúteo medio.", "Bs"],
[324, "Sentadilla pistola", "Piernas", "De pie sobre una pierna con la otra extendida al frente, baja controlado hasta la sentadilla profunda y sube sin apoyar la pierna libre. Requiere fuerza, equilibrio y movilidad.", "Bs"],
[8, "Gemelos de pie con mancuerna", "Piernas", "Sostén una mancuerna en una mano y sube de puntillas en un escalón o suelo, pausa arriba y baja hasta estirar el gemelo. Recorrido completo.", "Ls"],
[366, "Gemelos a una pierna", "Piernas", "Apoyado en una pierna, sube de puntillas lo más alto posible y baja lentamente hasta estirar. Agarra una pared para equilibrarte. Suma carga con una mancuerna.", "Bs"],
[340, "Gemelos en máquina de prensa", "Piernas", "Sentado en la prensa con las piernas casi extendidas, empuja la plataforma solo con las puntas de los pies y vuelve estirando el gemelo. Sin bloquear rodillas.", "Ls"],
[365, "Gemelos sentado en máquina", "Piernas", "Con las rodillas flexionadas bajo el soporte, sube los talones lo máximo posible y baja hasta estirar. Trabaja principalmente el sóleo.", "Ls"],
[465, "Gemelos de pie con barra", "Piernas", "Barra sobre la parte alta de la espalda, sube de puntillas en una plataforma y baja hasta estirar por debajo del escalón. Mantén el torso erguido.", "Ls"],
[774, "Curl femoral con toalla (deslizamiento)", "Piernas", "Tumbado boca arriba con los talones sobre toallas en suelo liso, eleva la cadera y desliza los talones alejándolos y acercándolos. Isquiotibiales en casa sin material.", "Bs"],
[959, "Curl femoral con banda", "Piernas", "Con la banda anclada, flexiona la rodilla llevando el talón hacia el glúteo y vuelve controlando. Mantén la cadera estable.", "Xc"],
[987, "Sentadilla sissy", "Piernas", "Inclina el torso hacia atrás mientras las rodillas avanzan y los talones se elevan. Gran aislamiento del cuádriceps. Agárrate a un apoyo para el equilibrio.", "Bs"],
[1085, "Elevación glúteo-isquio (glute ham raise)", "Piernas", "Con los pies anclados y el cuerpo recto, baja el torso controlado y sube flexionando las rodillas con isquiotibiales y glúteos. Muy exigente; usa ayuda si hace falta.", "Bs"],
[358, "Patada de glúteo en polea", "Piernas", "Con la tobillera en polea baja, extiende la pierna hacia atrás apretando el glúteo sin arquear la zona lumbar y vuelve controlando.", "Lc"],
[1139, "Hip thrust con banda", "Piernas", "Con una banda sobre los muslos y la espalda alta apoyada en un banco, empuja la cadera hacia arriba abriendo las rodillas contra la banda y aprieta arriba.", "Xs"],

// ───── HOMBROS (incluye trapecio) ─────
[37, "Press de hombros sentado con barra", "Hombros", "Sentado con la espalda apoyada, baja la barra a la altura de la barbilla y empuja hacia arriba hasta casi extender los codos. Abdomen firme; sin arquear la espalda.", "Lp"],
[116, "Press de hombros en máquina", "Hombros", "Ajusta el asiento para que los agarres queden a la altura de los hombros. Empuja hacia arriba sin bloquear los codos y baja controlando.", "Lp"],
[114, "Elevaciones laterales en polea", "Hombros", "De lado a la polea baja, eleva el brazo lateralmente hasta la altura del hombro con el codo ligeramente flexionado. Mantén la tensión constante al bajar.", "Lc"],
[409, "Elevaciones laterales en máquina", "Hombros", "Con los codos contra las almohadillas, abre los brazos hasta la altura del hombro y baja controlado. Aísla el deltoides lateral.", "Lc"],
[163, "Pájaros en máquina (deltoides posterior)", "Hombros", "Sentado de cara al respaldo, abre los brazos hacia atrás juntando las escápulas sin encoger los hombros. Vuelve controlando.", "Lc"],
[169, "Pájaros en polea", "Hombros", "Con dos poleas cruzadas, abre los brazos hacia atrás y afuera con los codos ligeramente flexionados, apretando el deltoides posterior.", "Lc"],
[172, "Remo al mentón en polea", "Hombros", "Sube la barra o cuerda pegada al cuerpo hasta la altura del pecho con los codos por encima de las muñecas. No subas más allá si molesta el hombro.", "Lt"],
[178, "Remo al mentón con mancuernas", "Hombros", "Con una mancuerna en cada mano frente a los muslos, sube los codos hacia arriba y afuera hasta la altura del pecho. Baja controlado.", "Lt"],
[1045, "Remo al mentón con barra", "Hombros", "Agarre a la anchura de los hombros, sube la barra pegada al torso hasta el pecho con los codos altos. Evita el balanceo y la elevación excesiva.", "Lt"],
[891, "Press Z con mancuernas", "Hombros", "Sentado en el suelo con las piernas extendidas, empuja las mancuernas sobre la cabeza sin apoyo en la espalda. Exige un core muy estable.", "Lp"],
[425, "Press de hombros a una mano con mancuerna", "Hombros", "De pie o sentado, empuja una mancuerna sobre la cabeza sin inclinar el torso y baja controlado. Trabaja hombro y estabilidad del core.", "Lp"],
[430, "Press de hombros alterno con mancuernas", "Hombros", "De pie, empuja una mancuerna hacia arriba mientras la otra baja, alternando brazos con el torso firme y sin arquear la espalda.", "Lp"],
[599, "Press militar con kettlebell a una mano", "Hombros", "Kettlebell en posición de rack, empuja hacia arriba hasta extender el brazo alineado con la oreja. Aprieta glúteo y abdomen; baja controlado.", "Lp"],
[741, "Press de hombros con kettlebell", "Hombros", "Con las kettlebells a la altura de los hombros y las muñecas rectas, empuja hacia arriba y baja de forma controlada. Estabilizador y fuerza de hombros.", "Lp"],
[665, "Press de hombros con banda", "Hombros", "Pisa la banda o anclala bajo los pies. Empuja los extremos sobre la cabeza hasta extender los brazos y baja despacio. Buena opción casera.", "Xp"],
[411, "Apertura de banda (band pull-apart)", "Hombros", "Sostén la banda al frente con los brazos extendidos y sepárala hasta el pecho juntando las escápulas. Vuelve despacio. Excelente para la postura y el deltoides posterior.", "Xt"],
[1102, "Pájaros con banda", "Hombros", "Con el torso inclinado y la banda bajo los pies, abre los brazos lateralmente hasta la altura de los hombros. Controla el retorno.", "Xt"],
[426, "Elevación en plano escapular (scaption)", "Hombros", "Eleva los brazos en diagonal (a 30° del frente) con los pulgares hacia arriba hasta la altura del hombro. Más seguro para el manguito rotador.", "Lc"],
[428, "Press cubano con mancuernas", "Hombros", "Sube las mancuernas con el codo alto hasta la altura de los hombros, rota los antebrazos hacia arriba y empuja sobre la cabeza. Trabaja hombro y manguito rotador.", "Lp"],
[963, "Rotación externa de hombro con banda", "Hombros", "Codo pegado al costado a 90°, rota el antebrazo hacia fuera contra la banda y vuelve despacio. Fortalece el manguito rotador y previene lesiones.", "Xc"],
[532, "Pájaros inclinados con mancuernas en banco", "Hombros", "Boca abajo en un banco inclinado, abre los brazos hacia los lados con los codos ligeramente flexionados, apretando el deltoides posterior.", "Lc"],
[533, "Elevación en Y en banco inclinado", "Hombros", "Boca abajo en un banco inclinado, eleva los brazos formando una Y con los pulgares hacia arriba. Trabaja el deltoides posterior y el trapecio inferior.", "Lc"],
[688, "Flexiones pike (hombros)", "Hombros", "Con las caderas elevadas formando una V invertida, baja la cabeza entre las manos y empuja hacia arriba. Gran ejercicio de hombros sin material.", "Bp"],
[48, "Push press con mancuernas", "Hombros", "Flexiona ligeramente las rodillas y empuja explosivamente con las piernas para impulsar las mancuernas sobre la cabeza. Baja controlando.", "Lp"],
[293, "Push press con barra", "Hombros", "Barra en los hombros, flexiona rodillas y extiende con fuerza para impulsar la barra sobre la cabeza. Bloquea arriba con el core firme.", "Lp"],
[144, "Elevaciones de 4 vías con mancuernas", "Hombros", "Combina elevación frontal, lateral, hacia atrás y cruzada con mancuernas ligeras. Mantén el control en cada vía sin balancear el torso.", "Lc"],
[148, "Encogimientos con mancuernas", "Hombros", "Mancuernas a los lados, sube los hombros hacia las orejas, pausa arriba y baja controlado. Sin rotar los hombros. Trabaja el trapecio superior.", "Lc"],
[151, "Encogimientos con barra", "Hombros", "Con la barra frente a los muslos, eleva los hombros verticalmente lo más alto posible y baja despacio. Sin flexionar los codos.", "Lc"],
[150, "Encogimientos en polea", "Hombros", "Frente a la polea baja, encoge los hombros hacia las orejas con la tensión constante del cable y baja controlado.", "Lc"],
[155, "Encogimientos en máquina", "Hombros", "Sentado o de pie en la máquina, eleva los hombros verticalmente y baja controlado. Útil para sobrecargar el trapecio con seguridad.", "Lc"],
[56, "Press de hombros de pie con mancuernas", "Hombros", "De pie con los pies al ancho de caderas, empuja las mancuernas desde los hombros hasta arriba sin arquear la espalda y baja controlado.", "Lp"],
];
